// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: AccountSummary.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Account       *string                `protobuf:"bytes,2,opt,name=account,proto3,oneof" json:"account,omitempty"`
	Tag           *string                `protobuf:"bytes,3,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Value         *string                `protobuf:"bytes,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Currency      *string                `protobuf:"bytes,5,opt,name=currency,proto3,oneof" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSummary) Reset() {
	*x = AccountSummary{}
	mi := &file_AccountSummary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSummary) ProtoMessage() {}

func (x *AccountSummary) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSummary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSummary.ProtoReflect.Descriptor instead.
func (*AccountSummary) Descriptor() ([]byte, []int) {
	return file_AccountSummary_proto_rawDescGZIP(), []int{0}
}

func (x *AccountSummary) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *AccountSummary) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *AccountSummary) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *AccountSummary) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *AccountSummary) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

var File_AccountSummary_proto protoreflect.FileDescriptor

const file_AccountSummary_proto_rawDesc = "" +
	"\n" +
	"\x14AccountSummary.proto\x12\bprotobuf\"\xd2\x01\n" +
	"\x0eAccountSummary\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12\x1d\n" +
	"\aaccount\x18\x02 \x01(\tH\x01R\aaccount\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x03 \x01(\tH\x02R\x03tag\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\tH\x03R\x05value\x88\x01\x01\x12\x1f\n" +
	"\bcurrency\x18\x05 \x01(\tH\x04R\bcurrency\x88\x01\x01B\b\n" +
	"\x06_reqIdB\n" +
	"\n" +
	"\b_accountB\x06\n" +
	"\x04_tagB\b\n" +
	"\x06_valueB\v\n" +
	"\t_currencyB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_AccountSummary_proto_rawDescOnce sync.Once
	file_AccountSummary_proto_rawDescData []byte
)

func file_AccountSummary_proto_rawDescGZIP() []byte {
	file_AccountSummary_proto_rawDescOnce.Do(func() {
		file_AccountSummary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AccountSummary_proto_rawDesc), len(file_AccountSummary_proto_rawDesc)))
	})
	return file_AccountSummary_proto_rawDescData
}

var file_AccountSummary_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AccountSummary_proto_goTypes = []any{
	(*AccountSummary)(nil), // 0: protobuf.AccountSummary
}
var file_AccountSummary_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AccountSummary_proto_init() }
func file_AccountSummary_proto_init() {
	if File_AccountSummary_proto != nil {
		return
	}
	file_AccountSummary_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AccountSummary_proto_rawDesc), len(file_AccountSummary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccountSummary_proto_goTypes,
		DependencyIndexes: file_AccountSummary_proto_depIdxs,
		MessageInfos:      file_AccountSummary_proto_msgTypes,
	}.Build()
	File_AccountSummary_proto = out.File
	file_AccountSummary_proto_goTypes = nil
	file_AccountSummary_proto_depIdxs = nil
}
