// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: AccountUpdatesMultiRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountUpdatesMultiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Account       *string                `protobuf:"bytes,2,opt,name=account,proto3,oneof" json:"account,omitempty"`
	ModelCode     *string                `protobuf:"bytes,3,opt,name=modelCode,proto3,oneof" json:"modelCode,omitempty"`
	LedgerAndNLV  *bool                  `protobuf:"varint,4,opt,name=ledgerAndNLV,proto3,oneof" json:"ledgerAndNLV,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountUpdatesMultiRequest) Reset() {
	*x = AccountUpdatesMultiRequest{}
	mi := &file_AccountUpdatesMultiRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUpdatesMultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUpdatesMultiRequest) ProtoMessage() {}

func (x *AccountUpdatesMultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccountUpdatesMultiRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUpdatesMultiRequest.ProtoReflect.Descriptor instead.
func (*AccountUpdatesMultiRequest) Descriptor() ([]byte, []int) {
	return file_AccountUpdatesMultiRequest_proto_rawDescGZIP(), []int{0}
}

func (x *AccountUpdatesMultiRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *AccountUpdatesMultiRequest) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *AccountUpdatesMultiRequest) GetModelCode() string {
	if x != nil && x.ModelCode != nil {
		return *x.ModelCode
	}
	return ""
}

func (x *AccountUpdatesMultiRequest) GetLedgerAndNLV() bool {
	if x != nil && x.LedgerAndNLV != nil {
		return *x.LedgerAndNLV
	}
	return false
}

var File_AccountUpdatesMultiRequest_proto protoreflect.FileDescriptor

var file_AccountUpdatesMultiRequest_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0xd7, 0x01, 0x0a,
	0x1a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x72,
	0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65,
	0x71, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x41, 0x6e, 0x64, 0x4e, 0x4c, 0x56, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03,
	0x52, 0x0c, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x4e, 0x4c, 0x56, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x65, 0x71, 0x49, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x41, 0x6e, 0x64, 0x4e, 0x4c, 0x56, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_AccountUpdatesMultiRequest_proto_rawDescOnce sync.Once
	file_AccountUpdatesMultiRequest_proto_rawDescData []byte
)

func file_AccountUpdatesMultiRequest_proto_rawDescGZIP() []byte {
	file_AccountUpdatesMultiRequest_proto_rawDescOnce.Do(func() {
		file_AccountUpdatesMultiRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AccountUpdatesMultiRequest_proto_rawDesc), len(file_AccountUpdatesMultiRequest_proto_rawDesc)))
	})
	return file_AccountUpdatesMultiRequest_proto_rawDescData
}

var file_AccountUpdatesMultiRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AccountUpdatesMultiRequest_proto_goTypes = []any{
	(*AccountUpdatesMultiRequest)(nil), // 0: protobuf.AccountUpdatesMultiRequest
}
var file_AccountUpdatesMultiRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AccountUpdatesMultiRequest_proto_init() }
func file_AccountUpdatesMultiRequest_proto_init() {
	if File_AccountUpdatesMultiRequest_proto != nil {
		return
	}
	file_AccountUpdatesMultiRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AccountUpdatesMultiRequest_proto_rawDesc), len(file_AccountUpdatesMultiRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccountUpdatesMultiRequest_proto_goTypes,
		DependencyIndexes: file_AccountUpdatesMultiRequest_proto_depIdxs,
		MessageInfos:      file_AccountUpdatesMultiRequest_proto_msgTypes,
	}.Build()
	File_AccountUpdatesMultiRequest_proto = out.File
	file_AccountUpdatesMultiRequest_proto_goTypes = nil
	file_AccountUpdatesMultiRequest_proto_depIdxs = nil
}
