// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: ApiConfig.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Precautions   *ApiPrecautionsConfig  `protobuf:"bytes,1,opt,name=precautions,proto3,oneof" json:"precautions,omitempty"`
	Settings      *ApiSettingsConfig     `protobuf:"bytes,2,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiConfig) Reset() {
	*x = ApiConfig{}
	mi := &file_ApiConfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiConfig) ProtoMessage() {}

func (x *ApiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ApiConfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiConfig.ProtoReflect.Descriptor instead.
func (*ApiConfig) Descriptor() ([]byte, []int) {
	return file_ApiConfig_proto_rawDescGZIP(), []int{0}
}

func (x *ApiConfig) GetPrecautions() *ApiPrecautionsConfig {
	if x != nil {
		return x.Precautions
	}
	return nil
}

func (x *ApiConfig) GetSettings() *ApiSettingsConfig {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_ApiConfig_proto protoreflect.FileDescriptor

const file_ApiConfig_proto_rawDesc = "" +
	"\n" +
	"\x0fApiConfig.proto\x12\bprotobuf\x1a\x1aApiPrecautionsConfig.proto\x1a\x17ApiSettingsConfig.proto\"\xad\x01\n" +
	"\tApiConfig\x12E\n" +
	"\vprecautions\x18\x01 \x01(\v2\x1e.protobuf.ApiPrecautionsConfigH\x00R\vprecautions\x88\x01\x01\x12<\n" +
	"\bsettings\x18\x02 \x01(\v2\x1b.protobuf.ApiSettingsConfigH\x01R\bsettings\x88\x01\x01B\x0e\n" +
	"\f_precautionsB\v\n" +
	"\t_settingsB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_ApiConfig_proto_rawDescOnce sync.Once
	file_ApiConfig_proto_rawDescData []byte
)

func file_ApiConfig_proto_rawDescGZIP() []byte {
	file_ApiConfig_proto_rawDescOnce.Do(func() {
		file_ApiConfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ApiConfig_proto_rawDesc), len(file_ApiConfig_proto_rawDesc)))
	})
	return file_ApiConfig_proto_rawDescData
}

var file_ApiConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ApiConfig_proto_goTypes = []any{
	(*ApiConfig)(nil),            // 0: protobuf.ApiConfig
	(*ApiPrecautionsConfig)(nil), // 1: protobuf.ApiPrecautionsConfig
	(*ApiSettingsConfig)(nil),    // 2: protobuf.ApiSettingsConfig
}
var file_ApiConfig_proto_depIdxs = []int32{
	1, // 0: protobuf.ApiConfig.precautions:type_name -> protobuf.ApiPrecautionsConfig
	2, // 1: protobuf.ApiConfig.settings:type_name -> protobuf.ApiSettingsConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ApiConfig_proto_init() }
func file_ApiConfig_proto_init() {
	if File_ApiConfig_proto != nil {
		return
	}
	file_ApiPrecautionsConfig_proto_init()
	file_ApiSettingsConfig_proto_init()
	file_ApiConfig_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ApiConfig_proto_rawDesc), len(file_ApiConfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ApiConfig_proto_goTypes,
		DependencyIndexes: file_ApiConfig_proto_depIdxs,
		MessageInfos:      file_ApiConfig_proto_msgTypes,
	}.Build()
	File_ApiConfig_proto = out.File
	file_ApiConfig_proto_goTypes = nil
	file_ApiConfig_proto_depIdxs = nil
}
