// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: AttachedOrders.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachedOrders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlOrderId     *int32                 `protobuf:"varint,1,opt,name=slOrderId,proto3,oneof" json:"slOrderId,omitempty"`
	SlOrderType   *string                `protobuf:"bytes,2,opt,name=slOrderType,proto3,oneof" json:"slOrderType,omitempty"`
	PtOrderId     *int32                 `protobuf:"varint,3,opt,name=ptOrderId,proto3,oneof" json:"ptOrderId,omitempty"`
	PtOrderType   *string                `protobuf:"bytes,4,opt,name=ptOrderType,proto3,oneof" json:"ptOrderType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachedOrders) Reset() {
	*x = AttachedOrders{}
	mi := &file_AttachedOrders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachedOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachedOrders) ProtoMessage() {}

func (x *AttachedOrders) ProtoReflect() protoreflect.Message {
	mi := &file_AttachedOrders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachedOrders.ProtoReflect.Descriptor instead.
func (*AttachedOrders) Descriptor() ([]byte, []int) {
	return file_AttachedOrders_proto_rawDescGZIP(), []int{0}
}

func (x *AttachedOrders) GetSlOrderId() int32 {
	if x != nil && x.SlOrderId != nil {
		return *x.SlOrderId
	}
	return 0
}

func (x *AttachedOrders) GetSlOrderType() string {
	if x != nil && x.SlOrderType != nil {
		return *x.SlOrderType
	}
	return ""
}

func (x *AttachedOrders) GetPtOrderId() int32 {
	if x != nil && x.PtOrderId != nil {
		return *x.PtOrderId
	}
	return 0
}

func (x *AttachedOrders) GetPtOrderType() string {
	if x != nil && x.PtOrderType != nil {
		return *x.PtOrderType
	}
	return ""
}

var File_AttachedOrders_proto protoreflect.FileDescriptor

const file_AttachedOrders_proto_rawDesc = "" +
	"\n" +
	"\x14AttachedOrders.proto\x12\bprotobuf\"\xe0\x01\n" +
	"\x0eAttachedOrders\x12!\n" +
	"\tslOrderId\x18\x01 \x01(\x05H\x00R\tslOrderId\x88\x01\x01\x12%\n" +
	"\vslOrderType\x18\x02 \x01(\tH\x01R\vslOrderType\x88\x01\x01\x12!\n" +
	"\tptOrderId\x18\x03 \x01(\x05H\x02R\tptOrderId\x88\x01\x01\x12%\n" +
	"\vptOrderType\x18\x04 \x01(\tH\x03R\vptOrderType\x88\x01\x01B\f\n" +
	"\n" +
	"_slOrderIdB\x0e\n" +
	"\f_slOrderTypeB\f\n" +
	"\n" +
	"_ptOrderIdB\x0e\n" +
	"\f_ptOrderTypeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_AttachedOrders_proto_rawDescOnce sync.Once
	file_AttachedOrders_proto_rawDescData []byte
)

func file_AttachedOrders_proto_rawDescGZIP() []byte {
	file_AttachedOrders_proto_rawDescOnce.Do(func() {
		file_AttachedOrders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AttachedOrders_proto_rawDesc), len(file_AttachedOrders_proto_rawDesc)))
	})
	return file_AttachedOrders_proto_rawDescData
}

var file_AttachedOrders_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AttachedOrders_proto_goTypes = []any{
	(*AttachedOrders)(nil), // 0: protobuf.AttachedOrders
}
var file_AttachedOrders_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AttachedOrders_proto_init() }
func file_AttachedOrders_proto_init() {
	if File_AttachedOrders_proto != nil {
		return
	}
	file_AttachedOrders_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AttachedOrders_proto_rawDesc), len(file_AttachedOrders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AttachedOrders_proto_goTypes,
		DependencyIndexes: file_AttachedOrders_proto_depIdxs,
		MessageInfos:      file_AttachedOrders_proto_msgTypes,
	}.Build()
	File_AttachedOrders_proto = out.File
	file_AttachedOrders_proto_goTypes = nil
	file_AttachedOrders_proto_depIdxs = nil
}
