// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: CalculateImpliedVolatilityRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateImpliedVolatilityRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ReqId                    *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Contract                 *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	OptionPrice              *float64               `protobuf:"fixed64,3,opt,name=optionPrice,proto3,oneof" json:"optionPrice,omitempty"`
	UnderPrice               *float64               `protobuf:"fixed64,4,opt,name=underPrice,proto3,oneof" json:"underPrice,omitempty"`
	ImpliedVolatilityOptions map[string]string      `protobuf:"bytes,5,rep,name=impliedVolatilityOptions,proto3" json:"impliedVolatilityOptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CalculateImpliedVolatilityRequest) Reset() {
	*x = CalculateImpliedVolatilityRequest{}
	mi := &file_CalculateImpliedVolatilityRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateImpliedVolatilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateImpliedVolatilityRequest) ProtoMessage() {}

func (x *CalculateImpliedVolatilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CalculateImpliedVolatilityRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateImpliedVolatilityRequest.ProtoReflect.Descriptor instead.
func (*CalculateImpliedVolatilityRequest) Descriptor() ([]byte, []int) {
	return file_CalculateImpliedVolatilityRequest_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateImpliedVolatilityRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *CalculateImpliedVolatilityRequest) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *CalculateImpliedVolatilityRequest) GetOptionPrice() float64 {
	if x != nil && x.OptionPrice != nil {
		return *x.OptionPrice
	}
	return 0
}

func (x *CalculateImpliedVolatilityRequest) GetUnderPrice() float64 {
	if x != nil && x.UnderPrice != nil {
		return *x.UnderPrice
	}
	return 0
}

func (x *CalculateImpliedVolatilityRequest) GetImpliedVolatilityOptions() map[string]string {
	if x != nil {
		return x.ImpliedVolatilityOptions
	}
	return nil
}

var File_CalculateImpliedVolatilityRequest_proto protoreflect.FileDescriptor

const file_CalculateImpliedVolatilityRequest_proto_rawDesc = "" +
	"\n" +
	"'CalculateImpliedVolatilityRequest.proto\x12\bprotobuf\x1a\x0eContract.proto\"\xca\x03\n" +
	"!CalculateImpliedVolatilityRequest\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x12.protobuf.ContractH\x01R\bcontract\x88\x01\x01\x12%\n" +
	"\voptionPrice\x18\x03 \x01(\x01H\x02R\voptionPrice\x88\x01\x01\x12#\n" +
	"\n" +
	"underPrice\x18\x04 \x01(\x01H\x03R\n" +
	"underPrice\x88\x01\x01\x12\x85\x01\n" +
	"\x18impliedVolatilityOptions\x18\x05 \x03(\v2I.protobuf.CalculateImpliedVolatilityRequest.ImpliedVolatilityOptionsEntryR\x18impliedVolatilityOptions\x1aK\n" +
	"\x1dImpliedVolatilityOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_contractB\x0e\n" +
	"\f_optionPriceB\r\n" +
	"\v_underPriceB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_CalculateImpliedVolatilityRequest_proto_rawDescOnce sync.Once
	file_CalculateImpliedVolatilityRequest_proto_rawDescData []byte
)

func file_CalculateImpliedVolatilityRequest_proto_rawDescGZIP() []byte {
	file_CalculateImpliedVolatilityRequest_proto_rawDescOnce.Do(func() {
		file_CalculateImpliedVolatilityRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CalculateImpliedVolatilityRequest_proto_rawDesc), len(file_CalculateImpliedVolatilityRequest_proto_rawDesc)))
	})
	return file_CalculateImpliedVolatilityRequest_proto_rawDescData
}

var file_CalculateImpliedVolatilityRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CalculateImpliedVolatilityRequest_proto_goTypes = []any{
	(*CalculateImpliedVolatilityRequest)(nil), // 0: protobuf.CalculateImpliedVolatilityRequest
	nil,              // 1: protobuf.CalculateImpliedVolatilityRequest.ImpliedVolatilityOptionsEntry
	(*Contract)(nil), // 2: protobuf.Contract
}
var file_CalculateImpliedVolatilityRequest_proto_depIdxs = []int32{
	2, // 0: protobuf.CalculateImpliedVolatilityRequest.contract:type_name -> protobuf.Contract
	1, // 1: protobuf.CalculateImpliedVolatilityRequest.impliedVolatilityOptions:type_name -> protobuf.CalculateImpliedVolatilityRequest.ImpliedVolatilityOptionsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CalculateImpliedVolatilityRequest_proto_init() }
func file_CalculateImpliedVolatilityRequest_proto_init() {
	if File_CalculateImpliedVolatilityRequest_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_CalculateImpliedVolatilityRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CalculateImpliedVolatilityRequest_proto_rawDesc), len(file_CalculateImpliedVolatilityRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CalculateImpliedVolatilityRequest_proto_goTypes,
		DependencyIndexes: file_CalculateImpliedVolatilityRequest_proto_depIdxs,
		MessageInfos:      file_CalculateImpliedVolatilityRequest_proto_msgTypes,
	}.Build()
	File_CalculateImpliedVolatilityRequest_proto = out.File
	file_CalculateImpliedVolatilityRequest_proto_goTypes = nil
	file_CalculateImpliedVolatilityRequest_proto_depIdxs = nil
}
