// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: ComboLeg.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComboLeg struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConId              *int32                 `protobuf:"varint,1,opt,name=conId,proto3,oneof" json:"conId,omitempty"`
	Ratio              *int32                 `protobuf:"varint,2,opt,name=ratio,proto3,oneof" json:"ratio,omitempty"`
	Action             *string                `protobuf:"bytes,3,opt,name=action,proto3,oneof" json:"action,omitempty"`
	Exchange           *string                `protobuf:"bytes,4,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	OpenClose          *int32                 `protobuf:"varint,5,opt,name=openClose,proto3,oneof" json:"openClose,omitempty"`
	ShortSalesSlot     *int32                 `protobuf:"varint,6,opt,name=shortSalesSlot,proto3,oneof" json:"shortSalesSlot,omitempty"`
	DesignatedLocation *string                `protobuf:"bytes,7,opt,name=designatedLocation,proto3,oneof" json:"designatedLocation,omitempty"`
	ExemptCode         *int32                 `protobuf:"varint,8,opt,name=exemptCode,proto3,oneof" json:"exemptCode,omitempty"`
	PerLegPrice        *float64               `protobuf:"fixed64,9,opt,name=perLegPrice,proto3,oneof" json:"perLegPrice,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComboLeg) Reset() {
	*x = ComboLeg{}
	mi := &file_ComboLeg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComboLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComboLeg) ProtoMessage() {}

func (x *ComboLeg) ProtoReflect() protoreflect.Message {
	mi := &file_ComboLeg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComboLeg.ProtoReflect.Descriptor instead.
func (*ComboLeg) Descriptor() ([]byte, []int) {
	return file_ComboLeg_proto_rawDescGZIP(), []int{0}
}

func (x *ComboLeg) GetConId() int32 {
	if x != nil && x.ConId != nil {
		return *x.ConId
	}
	return 0
}

func (x *ComboLeg) GetRatio() int32 {
	if x != nil && x.Ratio != nil {
		return *x.Ratio
	}
	return 0
}

func (x *ComboLeg) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *ComboLeg) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ComboLeg) GetOpenClose() int32 {
	if x != nil && x.OpenClose != nil {
		return *x.OpenClose
	}
	return 0
}

func (x *ComboLeg) GetShortSalesSlot() int32 {
	if x != nil && x.ShortSalesSlot != nil {
		return *x.ShortSalesSlot
	}
	return 0
}

func (x *ComboLeg) GetDesignatedLocation() string {
	if x != nil && x.DesignatedLocation != nil {
		return *x.DesignatedLocation
	}
	return ""
}

func (x *ComboLeg) GetExemptCode() int32 {
	if x != nil && x.ExemptCode != nil {
		return *x.ExemptCode
	}
	return 0
}

func (x *ComboLeg) GetPerLegPrice() float64 {
	if x != nil && x.PerLegPrice != nil {
		return *x.PerLegPrice
	}
	return 0
}

var File_ComboLeg_proto protoreflect.FileDescriptor

const file_ComboLeg_proto_rawDesc = "" +
	"\n" +
	"\x0eComboLeg.proto\x12\bprotobuf\"\xd2\x03\n" +
	"\bComboLeg\x12\x19\n" +
	"\x05conId\x18\x01 \x01(\x05H\x00R\x05conId\x88\x01\x01\x12\x19\n" +
	"\x05ratio\x18\x02 \x01(\x05H\x01R\x05ratio\x88\x01\x01\x12\x1b\n" +
	"\x06action\x18\x03 \x01(\tH\x02R\x06action\x88\x01\x01\x12\x1f\n" +
	"\bexchange\x18\x04 \x01(\tH\x03R\bexchange\x88\x01\x01\x12!\n" +
	"\topenClose\x18\x05 \x01(\x05H\x04R\topenClose\x88\x01\x01\x12+\n" +
	"\x0eshortSalesSlot\x18\x06 \x01(\x05H\x05R\x0eshortSalesSlot\x88\x01\x01\x123\n" +
	"\x12designatedLocation\x18\a \x01(\tH\x06R\x12designatedLocation\x88\x01\x01\x12#\n" +
	"\n" +
	"exemptCode\x18\b \x01(\x05H\aR\n" +
	"exemptCode\x88\x01\x01\x12%\n" +
	"\vperLegPrice\x18\t \x01(\x01H\bR\vperLegPrice\x88\x01\x01B\b\n" +
	"\x06_conIdB\b\n" +
	"\x06_ratioB\t\n" +
	"\a_actionB\v\n" +
	"\t_exchangeB\f\n" +
	"\n" +
	"_openCloseB\x11\n" +
	"\x0f_shortSalesSlotB\x15\n" +
	"\x13_designatedLocationB\r\n" +
	"\v_exemptCodeB\x0e\n" +
	"\f_perLegPriceB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_ComboLeg_proto_rawDescOnce sync.Once
	file_ComboLeg_proto_rawDescData []byte
)

func file_ComboLeg_proto_rawDescGZIP() []byte {
	file_ComboLeg_proto_rawDescOnce.Do(func() {
		file_ComboLeg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ComboLeg_proto_rawDesc), len(file_ComboLeg_proto_rawDesc)))
	})
	return file_ComboLeg_proto_rawDescData
}

var file_ComboLeg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ComboLeg_proto_goTypes = []any{
	(*ComboLeg)(nil), // 0: protobuf.ComboLeg
}
var file_ComboLeg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ComboLeg_proto_init() }
func file_ComboLeg_proto_init() {
	if File_ComboLeg_proto != nil {
		return
	}
	file_ComboLeg_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ComboLeg_proto_rawDesc), len(file_ComboLeg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ComboLeg_proto_goTypes,
		DependencyIndexes: file_ComboLeg_proto_depIdxs,
		MessageInfos:      file_ComboLeg_proto_msgTypes,
	}.Build()
	File_ComboLeg_proto = out.File
	file_ComboLeg_proto_goTypes = nil
	file_ComboLeg_proto_depIdxs = nil
}
