// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: CompletedOrdersEnd.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletedOrdersEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedOrdersEnd) Reset() {
	*x = CompletedOrdersEnd{}
	mi := &file_CompletedOrdersEnd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedOrdersEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedOrdersEnd) ProtoMessage() {}

func (x *CompletedOrdersEnd) ProtoReflect() protoreflect.Message {
	mi := &file_CompletedOrdersEnd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedOrdersEnd.ProtoReflect.Descriptor instead.
func (*CompletedOrdersEnd) Descriptor() ([]byte, []int) {
	return file_CompletedOrdersEnd_proto_rawDescGZIP(), []int{0}
}

var File_CompletedOrdersEnd_proto protoreflect.FileDescriptor

const file_CompletedOrdersEnd_proto_rawDesc = "" +
	"\n" +
	"\x18CompletedOrdersEnd.proto\x12\bprotobuf\"\x14\n" +
	"\x12CompletedOrdersEndB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_CompletedOrdersEnd_proto_rawDescOnce sync.Once
	file_CompletedOrdersEnd_proto_rawDescData []byte
)

func file_CompletedOrdersEnd_proto_rawDescGZIP() []byte {
	file_CompletedOrdersEnd_proto_rawDescOnce.Do(func() {
		file_CompletedOrdersEnd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CompletedOrdersEnd_proto_rawDesc), len(file_CompletedOrdersEnd_proto_rawDesc)))
	})
	return file_CompletedOrdersEnd_proto_rawDescData
}

var file_CompletedOrdersEnd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CompletedOrdersEnd_proto_goTypes = []any{
	(*CompletedOrdersEnd)(nil), // 0: protobuf.CompletedOrdersEnd
}
var file_CompletedOrdersEnd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CompletedOrdersEnd_proto_init() }
func file_CompletedOrdersEnd_proto_init() {
	if File_CompletedOrdersEnd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CompletedOrdersEnd_proto_rawDesc), len(file_CompletedOrdersEnd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CompletedOrdersEnd_proto_goTypes,
		DependencyIndexes: file_CompletedOrdersEnd_proto_depIdxs,
		MessageInfos:      file_CompletedOrdersEnd_proto_msgTypes,
	}.Build()
	File_CompletedOrdersEnd_proto = out.File
	file_CompletedOrdersEnd_proto_goTypes = nil
	file_CompletedOrdersEnd_proto_depIdxs = nil
}
