// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: Contract.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contract struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ConId                        *int32                 `protobuf:"varint,1,opt,name=conId,proto3,oneof" json:"conId,omitempty"`
	Symbol                       *string                `protobuf:"bytes,2,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	SecType                      *string                `protobuf:"bytes,3,opt,name=secType,proto3,oneof" json:"secType,omitempty"`
	LastTradeDateOrContractMonth *string                `protobuf:"bytes,4,opt,name=lastTradeDateOrContractMonth,proto3,oneof" json:"lastTradeDateOrContractMonth,omitempty"`
	Strike                       *float64               `protobuf:"fixed64,5,opt,name=strike,proto3,oneof" json:"strike,omitempty"`
	Right                        *string                `protobuf:"bytes,6,opt,name=right,proto3,oneof" json:"right,omitempty"`
	Multiplier                   *float64               `protobuf:"fixed64,7,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"`
	Exchange                     *string                `protobuf:"bytes,8,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	PrimaryExch                  *string                `protobuf:"bytes,9,opt,name=primaryExch,proto3,oneof" json:"primaryExch,omitempty"`
	Currency                     *string                `protobuf:"bytes,10,opt,name=currency,proto3,oneof" json:"currency,omitempty"`
	LocalSymbol                  *string                `protobuf:"bytes,11,opt,name=localSymbol,proto3,oneof" json:"localSymbol,omitempty"`
	TradingClass                 *string                `protobuf:"bytes,12,opt,name=tradingClass,proto3,oneof" json:"tradingClass,omitempty"`
	SecIdType                    *string                `protobuf:"bytes,13,opt,name=secIdType,proto3,oneof" json:"secIdType,omitempty"`
	SecId                        *string                `protobuf:"bytes,14,opt,name=secId,proto3,oneof" json:"secId,omitempty"`
	Description                  *string                `protobuf:"bytes,15,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IssuerId                     *string                `protobuf:"bytes,16,opt,name=issuerId,proto3,oneof" json:"issuerId,omitempty"`
	DeltaNeutralContract         *DeltaNeutralContract  `protobuf:"bytes,17,opt,name=deltaNeutralContract,proto3,oneof" json:"deltaNeutralContract,omitempty"`
	IncludeExpired               *bool                  `protobuf:"varint,18,opt,name=includeExpired,proto3,oneof" json:"includeExpired,omitempty"`
	ComboLegsDescrip             *string                `protobuf:"bytes,19,opt,name=comboLegsDescrip,proto3,oneof" json:"comboLegsDescrip,omitempty"`
	ComboLegs                    []*ComboLeg            `protobuf:"bytes,20,rep,name=comboLegs,proto3" json:"comboLegs,omitempty"`
	LastTradeDate                *string                `protobuf:"bytes,21,opt,name=lastTradeDate,proto3,oneof" json:"lastTradeDate,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_Contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_Contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_Contract_proto_rawDescGZIP(), []int{0}
}

func (x *Contract) GetConId() int32 {
	if x != nil && x.ConId != nil {
		return *x.ConId
	}
	return 0
}

func (x *Contract) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *Contract) GetSecType() string {
	if x != nil && x.SecType != nil {
		return *x.SecType
	}
	return ""
}

func (x *Contract) GetLastTradeDateOrContractMonth() string {
	if x != nil && x.LastTradeDateOrContractMonth != nil {
		return *x.LastTradeDateOrContractMonth
	}
	return ""
}

func (x *Contract) GetStrike() float64 {
	if x != nil && x.Strike != nil {
		return *x.Strike
	}
	return 0
}

func (x *Contract) GetRight() string {
	if x != nil && x.Right != nil {
		return *x.Right
	}
	return ""
}

func (x *Contract) GetMultiplier() float64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Contract) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *Contract) GetPrimaryExch() string {
	if x != nil && x.PrimaryExch != nil {
		return *x.PrimaryExch
	}
	return ""
}

func (x *Contract) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *Contract) GetLocalSymbol() string {
	if x != nil && x.LocalSymbol != nil {
		return *x.LocalSymbol
	}
	return ""
}

func (x *Contract) GetTradingClass() string {
	if x != nil && x.TradingClass != nil {
		return *x.TradingClass
	}
	return ""
}

func (x *Contract) GetSecIdType() string {
	if x != nil && x.SecIdType != nil {
		return *x.SecIdType
	}
	return ""
}

func (x *Contract) GetSecId() string {
	if x != nil && x.SecId != nil {
		return *x.SecId
	}
	return ""
}

func (x *Contract) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Contract) GetIssuerId() string {
	if x != nil && x.IssuerId != nil {
		return *x.IssuerId
	}
	return ""
}

func (x *Contract) GetDeltaNeutralContract() *DeltaNeutralContract {
	if x != nil {
		return x.DeltaNeutralContract
	}
	return nil
}

func (x *Contract) GetIncludeExpired() bool {
	if x != nil && x.IncludeExpired != nil {
		return *x.IncludeExpired
	}
	return false
}

func (x *Contract) GetComboLegsDescrip() string {
	if x != nil && x.ComboLegsDescrip != nil {
		return *x.ComboLegsDescrip
	}
	return ""
}

func (x *Contract) GetComboLegs() []*ComboLeg {
	if x != nil {
		return x.ComboLegs
	}
	return nil
}

func (x *Contract) GetLastTradeDate() string {
	if x != nil && x.LastTradeDate != nil {
		return *x.LastTradeDate
	}
	return ""
}

var File_Contract_proto protoreflect.FileDescriptor

const file_Contract_proto_rawDesc = "" +
	"\n" +
	"\x0eContract.proto\x12\bprotobuf\x1a\x0eComboLeg.proto\x1a\x1aDeltaNeutralContract.proto\"\x93\t\n" +
	"\bContract\x12\x19\n" +
	"\x05conId\x18\x01 \x01(\x05H\x00R\x05conId\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x02 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12\x1d\n" +
	"\asecType\x18\x03 \x01(\tH\x02R\asecType\x88\x01\x01\x12G\n" +
	"\x1clastTradeDateOrContractMonth\x18\x04 \x01(\tH\x03R\x1clastTradeDateOrContractMonth\x88\x01\x01\x12\x1b\n" +
	"\x06strike\x18\x05 \x01(\x01H\x04R\x06strike\x88\x01\x01\x12\x19\n" +
	"\x05right\x18\x06 \x01(\tH\x05R\x05right\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\a \x01(\x01H\x06R\n" +
	"multiplier\x88\x01\x01\x12\x1f\n" +
	"\bexchange\x18\b \x01(\tH\aR\bexchange\x88\x01\x01\x12%\n" +
	"\vprimaryExch\x18\t \x01(\tH\bR\vprimaryExch\x88\x01\x01\x12\x1f\n" +
	"\bcurrency\x18\n" +
	" \x01(\tH\tR\bcurrency\x88\x01\x01\x12%\n" +
	"\vlocalSymbol\x18\v \x01(\tH\n" +
	"R\vlocalSymbol\x88\x01\x01\x12'\n" +
	"\ftradingClass\x18\f \x01(\tH\vR\ftradingClass\x88\x01\x01\x12!\n" +
	"\tsecIdType\x18\r \x01(\tH\fR\tsecIdType\x88\x01\x01\x12\x19\n" +
	"\x05secId\x18\x0e \x01(\tH\rR\x05secId\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x0f \x01(\tH\x0eR\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bissuerId\x18\x10 \x01(\tH\x0fR\bissuerId\x88\x01\x01\x12W\n" +
	"\x14deltaNeutralContract\x18\x11 \x01(\v2\x1e.protobuf.DeltaNeutralContractH\x10R\x14deltaNeutralContract\x88\x01\x01\x12+\n" +
	"\x0eincludeExpired\x18\x12 \x01(\bH\x11R\x0eincludeExpired\x88\x01\x01\x12/\n" +
	"\x10comboLegsDescrip\x18\x13 \x01(\tH\x12R\x10comboLegsDescrip\x88\x01\x01\x120\n" +
	"\tcomboLegs\x18\x14 \x03(\v2\x12.protobuf.ComboLegR\tcomboLegs\x12)\n" +
	"\rlastTradeDate\x18\x15 \x01(\tH\x13R\rlastTradeDate\x88\x01\x01B\b\n" +
	"\x06_conIdB\t\n" +
	"\a_symbolB\n" +
	"\n" +
	"\b_secTypeB\x1f\n" +
	"\x1d_lastTradeDateOrContractMonthB\t\n" +
	"\a_strikeB\b\n" +
	"\x06_rightB\r\n" +
	"\v_multiplierB\v\n" +
	"\t_exchangeB\x0e\n" +
	"\f_primaryExchB\v\n" +
	"\t_currencyB\x0e\n" +
	"\f_localSymbolB\x0f\n" +
	"\r_tradingClassB\f\n" +
	"\n" +
	"_secIdTypeB\b\n" +
	"\x06_secIdB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_issuerIdB\x17\n" +
	"\x15_deltaNeutralContractB\x11\n" +
	"\x0f_includeExpiredB\x13\n" +
	"\x11_comboLegsDescripB\x10\n" +
	"\x0e_lastTradeDateB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_Contract_proto_rawDescOnce sync.Once
	file_Contract_proto_rawDescData []byte
)

func file_Contract_proto_rawDescGZIP() []byte {
	file_Contract_proto_rawDescOnce.Do(func() {
		file_Contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Contract_proto_rawDesc), len(file_Contract_proto_rawDesc)))
	})
	return file_Contract_proto_rawDescData
}

var file_Contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Contract_proto_goTypes = []any{
	(*Contract)(nil),             // 0: protobuf.Contract
	(*DeltaNeutralContract)(nil), // 1: protobuf.DeltaNeutralContract
	(*ComboLeg)(nil),             // 2: protobuf.ComboLeg
}
var file_Contract_proto_depIdxs = []int32{
	1, // 0: protobuf.Contract.deltaNeutralContract:type_name -> protobuf.DeltaNeutralContract
	2, // 1: protobuf.Contract.comboLegs:type_name -> protobuf.ComboLeg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Contract_proto_init() }
func file_Contract_proto_init() {
	if File_Contract_proto != nil {
		return
	}
	file_ComboLeg_proto_init()
	file_DeltaNeutralContract_proto_init()
	file_Contract_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Contract_proto_rawDesc), len(file_Contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Contract_proto_goTypes,
		DependencyIndexes: file_Contract_proto_depIdxs,
		MessageInfos:      file_Contract_proto_msgTypes,
	}.Build()
	File_Contract_proto = out.File
	file_Contract_proto_goTypes = nil
	file_Contract_proto_depIdxs = nil
}
