// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: CurrentTimeInMillisRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentTimeInMillisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentTimeInMillisRequest) Reset() {
	*x = CurrentTimeInMillisRequest{}
	mi := &file_CurrentTimeInMillisRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentTimeInMillisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentTimeInMillisRequest) ProtoMessage() {}

func (x *CurrentTimeInMillisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CurrentTimeInMillisRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentTimeInMillisRequest.ProtoReflect.Descriptor instead.
func (*CurrentTimeInMillisRequest) Descriptor() ([]byte, []int) {
	return file_CurrentTimeInMillisRequest_proto_rawDescGZIP(), []int{0}
}

var File_CurrentTimeInMillisRequest_proto protoreflect.FileDescriptor

var file_CurrentTimeInMillisRequest_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d,
	0x69, 0x6c, 0x6c, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x1c, 0x0a, 0x1a,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_CurrentTimeInMillisRequest_proto_rawDescOnce sync.Once
	file_CurrentTimeInMillisRequest_proto_rawDescData []byte
)

func file_CurrentTimeInMillisRequest_proto_rawDescGZIP() []byte {
	file_CurrentTimeInMillisRequest_proto_rawDescOnce.Do(func() {
		file_CurrentTimeInMillisRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CurrentTimeInMillisRequest_proto_rawDesc), len(file_CurrentTimeInMillisRequest_proto_rawDesc)))
	})
	return file_CurrentTimeInMillisRequest_proto_rawDescData
}

var file_CurrentTimeInMillisRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CurrentTimeInMillisRequest_proto_goTypes = []any{
	(*CurrentTimeInMillisRequest)(nil), // 0: protobuf.CurrentTimeInMillisRequest
}
var file_CurrentTimeInMillisRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CurrentTimeInMillisRequest_proto_init() }
func file_CurrentTimeInMillisRequest_proto_init() {
	if File_CurrentTimeInMillisRequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CurrentTimeInMillisRequest_proto_rawDesc), len(file_CurrentTimeInMillisRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CurrentTimeInMillisRequest_proto_goTypes,
		DependencyIndexes: file_CurrentTimeInMillisRequest_proto_depIdxs,
		MessageInfos:      file_CurrentTimeInMillisRequest_proto_msgTypes,
	}.Build()
	File_CurrentTimeInMillisRequest_proto = out.File
	file_CurrentTimeInMillisRequest_proto_goTypes = nil
	file_CurrentTimeInMillisRequest_proto_depIdxs = nil
}
