// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: CurrentTimeInMillis.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentTimeInMillis struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentTimeInMillis *int64                 `protobuf:"varint,1,opt,name=currentTimeInMillis,proto3,oneof" json:"currentTimeInMillis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CurrentTimeInMillis) Reset() {
	*x = CurrentTimeInMillis{}
	mi := &file_CurrentTimeInMillis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentTimeInMillis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentTimeInMillis) ProtoMessage() {}

func (x *CurrentTimeInMillis) ProtoReflect() protoreflect.Message {
	mi := &file_CurrentTimeInMillis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentTimeInMillis.ProtoReflect.Descriptor instead.
func (*CurrentTimeInMillis) Descriptor() ([]byte, []int) {
	return file_CurrentTimeInMillis_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentTimeInMillis) GetCurrentTimeInMillis() int64 {
	if x != nil && x.CurrentTimeInMillis != nil {
		return *x.CurrentTimeInMillis
	}
	return 0
}

var File_CurrentTimeInMillis_proto protoreflect.FileDescriptor

var file_CurrentTimeInMillis_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d,
	0x69, 0x6c, 0x6c, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x64, 0x0a, 0x13, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x35, 0x0a, 0x13,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x13, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x88, 0x01, 0x01, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_CurrentTimeInMillis_proto_rawDescOnce sync.Once
	file_CurrentTimeInMillis_proto_rawDescData []byte
)

func file_CurrentTimeInMillis_proto_rawDescGZIP() []byte {
	file_CurrentTimeInMillis_proto_rawDescOnce.Do(func() {
		file_CurrentTimeInMillis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CurrentTimeInMillis_proto_rawDesc), len(file_CurrentTimeInMillis_proto_rawDesc)))
	})
	return file_CurrentTimeInMillis_proto_rawDescData
}

var file_CurrentTimeInMillis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CurrentTimeInMillis_proto_goTypes = []any{
	(*CurrentTimeInMillis)(nil), // 0: protobuf.CurrentTimeInMillis
}
var file_CurrentTimeInMillis_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CurrentTimeInMillis_proto_init() }
func file_CurrentTimeInMillis_proto_init() {
	if File_CurrentTimeInMillis_proto != nil {
		return
	}
	file_CurrentTimeInMillis_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CurrentTimeInMillis_proto_rawDesc), len(file_CurrentTimeInMillis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CurrentTimeInMillis_proto_goTypes,
		DependencyIndexes: file_CurrentTimeInMillis_proto_depIdxs,
		MessageInfos:      file_CurrentTimeInMillis_proto_msgTypes,
	}.Build()
	File_CurrentTimeInMillis_proto = out.File
	file_CurrentTimeInMillis_proto_goTypes = nil
	file_CurrentTimeInMillis_proto_depIdxs = nil
}
