// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: DeltaNeutralContract.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeltaNeutralContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConId         *int32                 `protobuf:"varint,1,opt,name=conId,proto3,oneof" json:"conId,omitempty"`
	Delta         *float64               `protobuf:"fixed64,2,opt,name=delta,proto3,oneof" json:"delta,omitempty"`
	Price         *float64               `protobuf:"fixed64,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaNeutralContract) Reset() {
	*x = DeltaNeutralContract{}
	mi := &file_DeltaNeutralContract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaNeutralContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaNeutralContract) ProtoMessage() {}

func (x *DeltaNeutralContract) ProtoReflect() protoreflect.Message {
	mi := &file_DeltaNeutralContract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaNeutralContract.ProtoReflect.Descriptor instead.
func (*DeltaNeutralContract) Descriptor() ([]byte, []int) {
	return file_DeltaNeutralContract_proto_rawDescGZIP(), []int{0}
}

func (x *DeltaNeutralContract) GetConId() int32 {
	if x != nil && x.ConId != nil {
		return *x.ConId
	}
	return 0
}

func (x *DeltaNeutralContract) GetDelta() float64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *DeltaNeutralContract) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

var File_DeltaNeutralContract_proto protoreflect.FileDescriptor

var file_DeltaNeutralContract_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x85, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x74, 0x61,
	0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12,
	0x19, 0x0a, 0x05, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x05, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x05, 0x64, 0x65, 0x6c,
	0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_DeltaNeutralContract_proto_rawDescOnce sync.Once
	file_DeltaNeutralContract_proto_rawDescData []byte
)

func file_DeltaNeutralContract_proto_rawDescGZIP() []byte {
	file_DeltaNeutralContract_proto_rawDescOnce.Do(func() {
		file_DeltaNeutralContract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DeltaNeutralContract_proto_rawDesc), len(file_DeltaNeutralContract_proto_rawDesc)))
	})
	return file_DeltaNeutralContract_proto_rawDescData
}

var file_DeltaNeutralContract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DeltaNeutralContract_proto_goTypes = []any{
	(*DeltaNeutralContract)(nil), // 0: protobuf.DeltaNeutralContract
}
var file_DeltaNeutralContract_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DeltaNeutralContract_proto_init() }
func file_DeltaNeutralContract_proto_init() {
	if File_DeltaNeutralContract_proto != nil {
		return
	}
	file_DeltaNeutralContract_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DeltaNeutralContract_proto_rawDesc), len(file_DeltaNeutralContract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DeltaNeutralContract_proto_goTypes,
		DependencyIndexes: file_DeltaNeutralContract_proto_depIdxs,
		MessageInfos:      file_DeltaNeutralContract_proto_msgTypes,
	}.Build()
	File_DeltaNeutralContract_proto = out.File
	file_DeltaNeutralContract_proto_goTypes = nil
	file_DeltaNeutralContract_proto_depIdxs = nil
}
