// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: DepthMarketDataDescription.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepthMarketDataDescription struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exchange        *string                `protobuf:"bytes,1,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	SecType         *string                `protobuf:"bytes,2,opt,name=secType,proto3,oneof" json:"secType,omitempty"`
	ListingExch     *string                `protobuf:"bytes,3,opt,name=listingExch,proto3,oneof" json:"listingExch,omitempty"`
	ServiceDataType *string                `protobuf:"bytes,4,opt,name=serviceDataType,proto3,oneof" json:"serviceDataType,omitempty"`
	AggGroup        *int32                 `protobuf:"varint,5,opt,name=aggGroup,proto3,oneof" json:"aggGroup,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepthMarketDataDescription) Reset() {
	*x = DepthMarketDataDescription{}
	mi := &file_DepthMarketDataDescription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthMarketDataDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthMarketDataDescription) ProtoMessage() {}

func (x *DepthMarketDataDescription) ProtoReflect() protoreflect.Message {
	mi := &file_DepthMarketDataDescription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthMarketDataDescription.ProtoReflect.Descriptor instead.
func (*DepthMarketDataDescription) Descriptor() ([]byte, []int) {
	return file_DepthMarketDataDescription_proto_rawDescGZIP(), []int{0}
}

func (x *DepthMarketDataDescription) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *DepthMarketDataDescription) GetSecType() string {
	if x != nil && x.SecType != nil {
		return *x.SecType
	}
	return ""
}

func (x *DepthMarketDataDescription) GetListingExch() string {
	if x != nil && x.ListingExch != nil {
		return *x.ListingExch
	}
	return ""
}

func (x *DepthMarketDataDescription) GetServiceDataType() string {
	if x != nil && x.ServiceDataType != nil {
		return *x.ServiceDataType
	}
	return ""
}

func (x *DepthMarketDataDescription) GetAggGroup() int32 {
	if x != nil && x.AggGroup != nil {
		return *x.AggGroup
	}
	return 0
}

var File_DepthMarketDataDescription_proto protoreflect.FileDescriptor

const file_DepthMarketDataDescription_proto_rawDesc = "" +
	"\n" +
	" DepthMarketDataDescription.proto\x12\bprotobuf\"\x9d\x02\n" +
	"\x1aDepthMarketDataDescription\x12\x1f\n" +
	"\bexchange\x18\x01 \x01(\tH\x00R\bexchange\x88\x01\x01\x12\x1d\n" +
	"\asecType\x18\x02 \x01(\tH\x01R\asecType\x88\x01\x01\x12%\n" +
	"\vlistingExch\x18\x03 \x01(\tH\x02R\vlistingExch\x88\x01\x01\x12-\n" +
	"\x0fserviceDataType\x18\x04 \x01(\tH\x03R\x0fserviceDataType\x88\x01\x01\x12\x1f\n" +
	"\baggGroup\x18\x05 \x01(\x05H\x04R\baggGroup\x88\x01\x01B\v\n" +
	"\t_exchangeB\n" +
	"\n" +
	"\b_secTypeB\x0e\n" +
	"\f_listingExchB\x12\n" +
	"\x10_serviceDataTypeB\v\n" +
	"\t_aggGroupB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_DepthMarketDataDescription_proto_rawDescOnce sync.Once
	file_DepthMarketDataDescription_proto_rawDescData []byte
)

func file_DepthMarketDataDescription_proto_rawDescGZIP() []byte {
	file_DepthMarketDataDescription_proto_rawDescOnce.Do(func() {
		file_DepthMarketDataDescription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DepthMarketDataDescription_proto_rawDesc), len(file_DepthMarketDataDescription_proto_rawDesc)))
	})
	return file_DepthMarketDataDescription_proto_rawDescData
}

var file_DepthMarketDataDescription_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DepthMarketDataDescription_proto_goTypes = []any{
	(*DepthMarketDataDescription)(nil), // 0: protobuf.DepthMarketDataDescription
}
var file_DepthMarketDataDescription_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DepthMarketDataDescription_proto_init() }
func file_DepthMarketDataDescription_proto_init() {
	if File_DepthMarketDataDescription_proto != nil {
		return
	}
	file_DepthMarketDataDescription_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DepthMarketDataDescription_proto_rawDesc), len(file_DepthMarketDataDescription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DepthMarketDataDescription_proto_goTypes,
		DependencyIndexes: file_DepthMarketDataDescription_proto_depIdxs,
		MessageInfos:      file_DepthMarketDataDescription_proto_msgTypes,
	}.Build()
	File_DepthMarketDataDescription_proto = out.File
	file_DepthMarketDataDescription_proto_goTypes = nil
	file_DepthMarketDataDescription_proto_depIdxs = nil
}
