// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: DepthMarketDataDescription.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepthMarketDataDescription struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exchange        *string                `protobuf:"bytes,1,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	SecType         *string                `protobuf:"bytes,2,opt,name=secType,proto3,oneof" json:"secType,omitempty"`
	ListingExch     *string                `protobuf:"bytes,3,opt,name=listingExch,proto3,oneof" json:"listingExch,omitempty"`
	ServiceDataType *string                `protobuf:"bytes,4,opt,name=serviceDataType,proto3,oneof" json:"serviceDataType,omitempty"`
	AggGroup        *int32                 `protobuf:"varint,5,opt,name=aggGroup,proto3,oneof" json:"aggGroup,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepthMarketDataDescription) Reset() {
	*x = DepthMarketDataDescription{}
	mi := &file_DepthMarketDataDescription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthMarketDataDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthMarketDataDescription) ProtoMessage() {}

func (x *DepthMarketDataDescription) ProtoReflect() protoreflect.Message {
	mi := &file_DepthMarketDataDescription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthMarketDataDescription.ProtoReflect.Descriptor instead.
func (*DepthMarketDataDescription) Descriptor() ([]byte, []int) {
	return file_DepthMarketDataDescription_proto_rawDescGZIP(), []int{0}
}

func (x *DepthMarketDataDescription) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *DepthMarketDataDescription) GetSecType() string {
	if x != nil && x.SecType != nil {
		return *x.SecType
	}
	return ""
}

func (x *DepthMarketDataDescription) GetListingExch() string {
	if x != nil && x.ListingExch != nil {
		return *x.ListingExch
	}
	return ""
}

func (x *DepthMarketDataDescription) GetServiceDataType() string {
	if x != nil && x.ServiceDataType != nil {
		return *x.ServiceDataType
	}
	return ""
}

func (x *DepthMarketDataDescription) GetAggGroup() int32 {
	if x != nil && x.AggGroup != nil {
		return *x.AggGroup
	}
	return 0
}

var File_DepthMarketDataDescription_proto protoreflect.FileDescriptor

var file_DepthMarketDataDescription_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x9d, 0x02, 0x0a,
	0x1a, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x08, 0x65,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07,
	0x73, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x07, 0x73, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x6c,
	0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x63, 0x68, 0x88,
	0x01, 0x01, 0x12, 0x2d, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x1f, 0x0a, 0x08, 0x61, 0x67, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x04, 0x52, 0x08, 0x61, 0x67, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x88,
	0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x65, 0x63, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x63, 0x68, 0x42, 0x12, 0x0a, 0x10, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x61, 0x67, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_DepthMarketDataDescription_proto_rawDescOnce sync.Once
	file_DepthMarketDataDescription_proto_rawDescData []byte
)

func file_DepthMarketDataDescription_proto_rawDescGZIP() []byte {
	file_DepthMarketDataDescription_proto_rawDescOnce.Do(func() {
		file_DepthMarketDataDescription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DepthMarketDataDescription_proto_rawDesc), len(file_DepthMarketDataDescription_proto_rawDesc)))
	})
	return file_DepthMarketDataDescription_proto_rawDescData
}

var file_DepthMarketDataDescription_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DepthMarketDataDescription_proto_goTypes = []any{
	(*DepthMarketDataDescription)(nil), // 0: protobuf.DepthMarketDataDescription
}
var file_DepthMarketDataDescription_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DepthMarketDataDescription_proto_init() }
func file_DepthMarketDataDescription_proto_init() {
	if File_DepthMarketDataDescription_proto != nil {
		return
	}
	file_DepthMarketDataDescription_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DepthMarketDataDescription_proto_rawDesc), len(file_DepthMarketDataDescription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DepthMarketDataDescription_proto_goTypes,
		DependencyIndexes: file_DepthMarketDataDescription_proto_depIdxs,
		MessageInfos:      file_DepthMarketDataDescription_proto_msgTypes,
	}.Build()
	File_DepthMarketDataDescription_proto = out.File
	file_DepthMarketDataDescription_proto_goTypes = nil
	file_DepthMarketDataDescription_proto_depIdxs = nil
}
