// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: ExerciseOptionsRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExerciseOptionsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OrderId              *int32                 `protobuf:"varint,1,opt,name=orderId,proto3,oneof" json:"orderId,omitempty"`
	Contract             *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	ExerciseAction       *int32                 `protobuf:"varint,3,opt,name=exerciseAction,proto3,oneof" json:"exerciseAction,omitempty"`
	ExerciseQuantity     *int32                 `protobuf:"varint,4,opt,name=exerciseQuantity,proto3,oneof" json:"exerciseQuantity,omitempty"`
	Account              *string                `protobuf:"bytes,5,opt,name=account,proto3,oneof" json:"account,omitempty"`
	Override             *bool                  `protobuf:"varint,6,opt,name=override,proto3,oneof" json:"override,omitempty"`
	ManualOrderTime      *string                `protobuf:"bytes,7,opt,name=manualOrderTime,proto3,oneof" json:"manualOrderTime,omitempty"`
	CustomerAccount      *string                `protobuf:"bytes,8,opt,name=customerAccount,proto3,oneof" json:"customerAccount,omitempty"`
	ProfessionalCustomer *bool                  `protobuf:"varint,9,opt,name=professionalCustomer,proto3,oneof" json:"professionalCustomer,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExerciseOptionsRequest) Reset() {
	*x = ExerciseOptionsRequest{}
	mi := &file_ExerciseOptionsRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseOptionsRequest) ProtoMessage() {}

func (x *ExerciseOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ExerciseOptionsRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseOptionsRequest.ProtoReflect.Descriptor instead.
func (*ExerciseOptionsRequest) Descriptor() ([]byte, []int) {
	return file_ExerciseOptionsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *ExerciseOptionsRequest) GetOrderId() int32 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *ExerciseOptionsRequest) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ExerciseOptionsRequest) GetExerciseAction() int32 {
	if x != nil && x.ExerciseAction != nil {
		return *x.ExerciseAction
	}
	return 0
}

func (x *ExerciseOptionsRequest) GetExerciseQuantity() int32 {
	if x != nil && x.ExerciseQuantity != nil {
		return *x.ExerciseQuantity
	}
	return 0
}

func (x *ExerciseOptionsRequest) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *ExerciseOptionsRequest) GetOverride() bool {
	if x != nil && x.Override != nil {
		return *x.Override
	}
	return false
}

func (x *ExerciseOptionsRequest) GetManualOrderTime() string {
	if x != nil && x.ManualOrderTime != nil {
		return *x.ManualOrderTime
	}
	return ""
}

func (x *ExerciseOptionsRequest) GetCustomerAccount() string {
	if x != nil && x.CustomerAccount != nil {
		return *x.CustomerAccount
	}
	return ""
}

func (x *ExerciseOptionsRequest) GetProfessionalCustomer() bool {
	if x != nil && x.ProfessionalCustomer != nil {
		return *x.ProfessionalCustomer
	}
	return false
}

var File_ExerciseOptionsRequest_proto protoreflect.FileDescriptor

const file_ExerciseOptionsRequest_proto_rawDesc = "" +
	"\n" +
	"\x1cExerciseOptionsRequest.proto\x12\bprotobuf\x1a\x0eContract.proto\"\xbc\x04\n" +
	"\x16ExerciseOptionsRequest\x12\x1d\n" +
	"\aorderId\x18\x01 \x01(\x05H\x00R\aorderId\x88\x01\x01\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x12.protobuf.ContractH\x01R\bcontract\x88\x01\x01\x12+\n" +
	"\x0eexerciseAction\x18\x03 \x01(\x05H\x02R\x0eexerciseAction\x88\x01\x01\x12/\n" +
	"\x10exerciseQuantity\x18\x04 \x01(\x05H\x03R\x10exerciseQuantity\x88\x01\x01\x12\x1d\n" +
	"\aaccount\x18\x05 \x01(\tH\x04R\aaccount\x88\x01\x01\x12\x1f\n" +
	"\boverride\x18\x06 \x01(\bH\x05R\boverride\x88\x01\x01\x12-\n" +
	"\x0fmanualOrderTime\x18\a \x01(\tH\x06R\x0fmanualOrderTime\x88\x01\x01\x12-\n" +
	"\x0fcustomerAccount\x18\b \x01(\tH\aR\x0fcustomerAccount\x88\x01\x01\x127\n" +
	"\x14professionalCustomer\x18\t \x01(\bH\bR\x14professionalCustomer\x88\x01\x01B\n" +
	"\n" +
	"\b_orderIdB\v\n" +
	"\t_contractB\x11\n" +
	"\x0f_exerciseActionB\x13\n" +
	"\x11_exerciseQuantityB\n" +
	"\n" +
	"\b_accountB\v\n" +
	"\t_overrideB\x12\n" +
	"\x10_manualOrderTimeB\x12\n" +
	"\x10_customerAccountB\x17\n" +
	"\x15_professionalCustomerB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_ExerciseOptionsRequest_proto_rawDescOnce sync.Once
	file_ExerciseOptionsRequest_proto_rawDescData []byte
)

func file_ExerciseOptionsRequest_proto_rawDescGZIP() []byte {
	file_ExerciseOptionsRequest_proto_rawDescOnce.Do(func() {
		file_ExerciseOptionsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ExerciseOptionsRequest_proto_rawDesc), len(file_ExerciseOptionsRequest_proto_rawDesc)))
	})
	return file_ExerciseOptionsRequest_proto_rawDescData
}

var file_ExerciseOptionsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ExerciseOptionsRequest_proto_goTypes = []any{
	(*ExerciseOptionsRequest)(nil), // 0: protobuf.ExerciseOptionsRequest
	(*Contract)(nil),               // 1: protobuf.Contract
}
var file_ExerciseOptionsRequest_proto_depIdxs = []int32{
	1, // 0: protobuf.ExerciseOptionsRequest.contract:type_name -> protobuf.Contract
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ExerciseOptionsRequest_proto_init() }
func file_ExerciseOptionsRequest_proto_init() {
	if File_ExerciseOptionsRequest_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_ExerciseOptionsRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ExerciseOptionsRequest_proto_rawDesc), len(file_ExerciseOptionsRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ExerciseOptionsRequest_proto_goTypes,
		DependencyIndexes: file_ExerciseOptionsRequest_proto_depIdxs,
		MessageInfos:      file_ExerciseOptionsRequest_proto_msgTypes,
	}.Build()
	File_ExerciseOptionsRequest_proto = out.File
	file_ExerciseOptionsRequest_proto_goTypes = nil
	file_ExerciseOptionsRequest_proto_depIdxs = nil
}
