// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: FamilyCode.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     *string                `protobuf:"bytes,1,opt,name=accountId,proto3,oneof" json:"accountId,omitempty"`
	FamilyCode    *string                `protobuf:"bytes,2,opt,name=familyCode,proto3,oneof" json:"familyCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyCode) Reset() {
	*x = FamilyCode{}
	mi := &file_FamilyCode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyCode) ProtoMessage() {}

func (x *FamilyCode) ProtoReflect() protoreflect.Message {
	mi := &file_FamilyCode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyCode.ProtoReflect.Descriptor instead.
func (*FamilyCode) Descriptor() ([]byte, []int) {
	return file_FamilyCode_proto_rawDescGZIP(), []int{0}
}

func (x *FamilyCode) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *FamilyCode) GetFamilyCode() string {
	if x != nil && x.FamilyCode != nil {
		return *x.FamilyCode
	}
	return ""
}

var File_FamilyCode_proto protoreflect.FileDescriptor

const file_FamilyCode_proto_rawDesc = "" +
	"\n" +
	"\x10FamilyCode.proto\x12\bprotobuf\"q\n" +
	"\n" +
	"FamilyCode\x12!\n" +
	"\taccountId\x18\x01 \x01(\tH\x00R\taccountId\x88\x01\x01\x12#\n" +
	"\n" +
	"familyCode\x18\x02 \x01(\tH\x01R\n" +
	"familyCode\x88\x01\x01B\f\n" +
	"\n" +
	"_accountIdB\r\n" +
	"\v_familyCodeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_FamilyCode_proto_rawDescOnce sync.Once
	file_FamilyCode_proto_rawDescData []byte
)

func file_FamilyCode_proto_rawDescGZIP() []byte {
	file_FamilyCode_proto_rawDescOnce.Do(func() {
		file_FamilyCode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FamilyCode_proto_rawDesc), len(file_FamilyCode_proto_rawDesc)))
	})
	return file_FamilyCode_proto_rawDescData
}

var file_FamilyCode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FamilyCode_proto_goTypes = []any{
	(*FamilyCode)(nil), // 0: protobuf.FamilyCode
}
var file_FamilyCode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_FamilyCode_proto_init() }
func file_FamilyCode_proto_init() {
	if File_FamilyCode_proto != nil {
		return
	}
	file_FamilyCode_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FamilyCode_proto_rawDesc), len(file_FamilyCode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FamilyCode_proto_goTypes,
		DependencyIndexes: file_FamilyCode_proto_depIdxs,
		MessageInfos:      file_FamilyCode_proto_msgTypes,
	}.Build()
	File_FamilyCode_proto = out.File
	file_FamilyCode_proto_goTypes = nil
	file_FamilyCode_proto_depIdxs = nil
}
