// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: FAReplace.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FAReplace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	FaDataType    *int32                 `protobuf:"varint,2,opt,name=faDataType,proto3,oneof" json:"faDataType,omitempty"`
	Xml           *string                `protobuf:"bytes,3,opt,name=xml,proto3,oneof" json:"xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FAReplace) Reset() {
	*x = FAReplace{}
	mi := &file_FAReplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FAReplace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FAReplace) ProtoMessage() {}

func (x *FAReplace) ProtoReflect() protoreflect.Message {
	mi := &file_FAReplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FAReplace.ProtoReflect.Descriptor instead.
func (*FAReplace) Descriptor() ([]byte, []int) {
	return file_FAReplace_proto_rawDescGZIP(), []int{0}
}

func (x *FAReplace) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *FAReplace) GetFaDataType() int32 {
	if x != nil && x.FaDataType != nil {
		return *x.FaDataType
	}
	return 0
}

func (x *FAReplace) GetXml() string {
	if x != nil && x.Xml != nil {
		return *x.Xml
	}
	return ""
}

var File_FAReplace_proto protoreflect.FileDescriptor

const file_FAReplace_proto_rawDesc = "" +
	"\n" +
	"\x0fFAReplace.proto\x12\bprotobuf\"\x83\x01\n" +
	"\tFAReplace\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12#\n" +
	"\n" +
	"faDataType\x18\x02 \x01(\x05H\x01R\n" +
	"faDataType\x88\x01\x01\x12\x15\n" +
	"\x03xml\x18\x03 \x01(\tH\x02R\x03xml\x88\x01\x01B\b\n" +
	"\x06_reqIdB\r\n" +
	"\v_faDataTypeB\x06\n" +
	"\x04_xmlB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_FAReplace_proto_rawDescOnce sync.Once
	file_FAReplace_proto_rawDescData []byte
)

func file_FAReplace_proto_rawDescGZIP() []byte {
	file_FAReplace_proto_rawDescOnce.Do(func() {
		file_FAReplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FAReplace_proto_rawDesc), len(file_FAReplace_proto_rawDesc)))
	})
	return file_FAReplace_proto_rawDescData
}

var file_FAReplace_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FAReplace_proto_goTypes = []any{
	(*FAReplace)(nil), // 0: protobuf.FAReplace
}
var file_FAReplace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_FAReplace_proto_init() }
func file_FAReplace_proto_init() {
	if File_FAReplace_proto != nil {
		return
	}
	file_FAReplace_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FAReplace_proto_rawDesc), len(file_FAReplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FAReplace_proto_goTypes,
		DependencyIndexes: file_FAReplace_proto_depIdxs,
		MessageInfos:      file_FAReplace_proto_msgTypes,
	}.Build()
	File_FAReplace_proto = out.File
	file_FAReplace_proto_goTypes = nil
	file_FAReplace_proto_depIdxs = nil
}
