// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HeadTimestampRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeadTimestampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Contract      *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	UseRTH        *bool                  `protobuf:"varint,3,opt,name=useRTH,proto3,oneof" json:"useRTH,omitempty"`
	WhatToShow    *string                `protobuf:"bytes,4,opt,name=whatToShow,proto3,oneof" json:"whatToShow,omitempty"`
	FormatDate    *int32                 `protobuf:"varint,5,opt,name=formatDate,proto3,oneof" json:"formatDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadTimestampRequest) Reset() {
	*x = HeadTimestampRequest{}
	mi := &file_HeadTimestampRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadTimestampRequest) ProtoMessage() {}

func (x *HeadTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HeadTimestampRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadTimestampRequest.ProtoReflect.Descriptor instead.
func (*HeadTimestampRequest) Descriptor() ([]byte, []int) {
	return file_HeadTimestampRequest_proto_rawDescGZIP(), []int{0}
}

func (x *HeadTimestampRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HeadTimestampRequest) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *HeadTimestampRequest) GetUseRTH() bool {
	if x != nil && x.UseRTH != nil {
		return *x.UseRTH
	}
	return false
}

func (x *HeadTimestampRequest) GetWhatToShow() string {
	if x != nil && x.WhatToShow != nil {
		return *x.WhatToShow
	}
	return ""
}

func (x *HeadTimestampRequest) GetFormatDate() int32 {
	if x != nil && x.FormatDate != nil {
		return *x.FormatDate
	}
	return 0
}

var File_HeadTimestampRequest_proto protoreflect.FileDescriptor

const file_HeadTimestampRequest_proto_rawDesc = "" +
	"\n" +
	"\x1aHeadTimestampRequest.proto\x12\bprotobuf\x1a\x0eContract.proto\"\x8d\x02\n" +
	"\x14HeadTimestampRequest\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x12.protobuf.ContractH\x01R\bcontract\x88\x01\x01\x12\x1b\n" +
	"\x06useRTH\x18\x03 \x01(\bH\x02R\x06useRTH\x88\x01\x01\x12#\n" +
	"\n" +
	"whatToShow\x18\x04 \x01(\tH\x03R\n" +
	"whatToShow\x88\x01\x01\x12#\n" +
	"\n" +
	"formatDate\x18\x05 \x01(\x05H\x04R\n" +
	"formatDate\x88\x01\x01B\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_contractB\t\n" +
	"\a_useRTHB\r\n" +
	"\v_whatToShowB\r\n" +
	"\v_formatDateB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HeadTimestampRequest_proto_rawDescOnce sync.Once
	file_HeadTimestampRequest_proto_rawDescData []byte
)

func file_HeadTimestampRequest_proto_rawDescGZIP() []byte {
	file_HeadTimestampRequest_proto_rawDescOnce.Do(func() {
		file_HeadTimestampRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HeadTimestampRequest_proto_rawDesc), len(file_HeadTimestampRequest_proto_rawDesc)))
	})
	return file_HeadTimestampRequest_proto_rawDescData
}

var file_HeadTimestampRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HeadTimestampRequest_proto_goTypes = []any{
	(*HeadTimestampRequest)(nil), // 0: protobuf.HeadTimestampRequest
	(*Contract)(nil),             // 1: protobuf.Contract
}
var file_HeadTimestampRequest_proto_depIdxs = []int32{
	1, // 0: protobuf.HeadTimestampRequest.contract:type_name -> protobuf.Contract
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_HeadTimestampRequest_proto_init() }
func file_HeadTimestampRequest_proto_init() {
	if File_HeadTimestampRequest_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_HeadTimestampRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HeadTimestampRequest_proto_rawDesc), len(file_HeadTimestampRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HeadTimestampRequest_proto_goTypes,
		DependencyIndexes: file_HeadTimestampRequest_proto_depIdxs,
		MessageInfos:      file_HeadTimestampRequest_proto_msgTypes,
	}.Build()
	File_HeadTimestampRequest_proto = out.File
	file_HeadTimestampRequest_proto_goTypes = nil
	file_HeadTimestampRequest_proto_depIdxs = nil
}
