// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalTicksRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalTicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Contract      *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	StartDateTime *string                `protobuf:"bytes,3,opt,name=startDateTime,proto3,oneof" json:"startDateTime,omitempty"`
	EndDateTime   *string                `protobuf:"bytes,4,opt,name=endDateTime,proto3,oneof" json:"endDateTime,omitempty"`
	NumberOfTicks *int32                 `protobuf:"varint,5,opt,name=numberOfTicks,proto3,oneof" json:"numberOfTicks,omitempty"`
	WhatToShow    *string                `protobuf:"bytes,6,opt,name=whatToShow,proto3,oneof" json:"whatToShow,omitempty"`
	UseRTH        *bool                  `protobuf:"varint,7,opt,name=useRTH,proto3,oneof" json:"useRTH,omitempty"`
	IgnoreSize    *bool                  `protobuf:"varint,8,opt,name=ignoreSize,proto3,oneof" json:"ignoreSize,omitempty"`
	MiscOptions   map[string]string      `protobuf:"bytes,9,rep,name=miscOptions,proto3" json:"miscOptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalTicksRequest) Reset() {
	*x = HistoricalTicksRequest{}
	mi := &file_HistoricalTicksRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalTicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalTicksRequest) ProtoMessage() {}

func (x *HistoricalTicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalTicksRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalTicksRequest.ProtoReflect.Descriptor instead.
func (*HistoricalTicksRequest) Descriptor() ([]byte, []int) {
	return file_HistoricalTicksRequest_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalTicksRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HistoricalTicksRequest) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *HistoricalTicksRequest) GetStartDateTime() string {
	if x != nil && x.StartDateTime != nil {
		return *x.StartDateTime
	}
	return ""
}

func (x *HistoricalTicksRequest) GetEndDateTime() string {
	if x != nil && x.EndDateTime != nil {
		return *x.EndDateTime
	}
	return ""
}

func (x *HistoricalTicksRequest) GetNumberOfTicks() int32 {
	if x != nil && x.NumberOfTicks != nil {
		return *x.NumberOfTicks
	}
	return 0
}

func (x *HistoricalTicksRequest) GetWhatToShow() string {
	if x != nil && x.WhatToShow != nil {
		return *x.WhatToShow
	}
	return ""
}

func (x *HistoricalTicksRequest) GetUseRTH() bool {
	if x != nil && x.UseRTH != nil {
		return *x.UseRTH
	}
	return false
}

func (x *HistoricalTicksRequest) GetIgnoreSize() bool {
	if x != nil && x.IgnoreSize != nil {
		return *x.IgnoreSize
	}
	return false
}

func (x *HistoricalTicksRequest) GetMiscOptions() map[string]string {
	if x != nil {
		return x.MiscOptions
	}
	return nil
}

var File_HistoricalTicksRequest_proto protoreflect.FileDescriptor

const file_HistoricalTicksRequest_proto_rawDesc = "" +
	"\n" +
	"\x1cHistoricalTicksRequest.proto\x12\bprotobuf\x1a\x0eContract.proto\"\xd5\x04\n" +
	"\x16HistoricalTicksRequest\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x12.protobuf.ContractH\x01R\bcontract\x88\x01\x01\x12)\n" +
	"\rstartDateTime\x18\x03 \x01(\tH\x02R\rstartDateTime\x88\x01\x01\x12%\n" +
	"\vendDateTime\x18\x04 \x01(\tH\x03R\vendDateTime\x88\x01\x01\x12)\n" +
	"\rnumberOfTicks\x18\x05 \x01(\x05H\x04R\rnumberOfTicks\x88\x01\x01\x12#\n" +
	"\n" +
	"whatToShow\x18\x06 \x01(\tH\x05R\n" +
	"whatToShow\x88\x01\x01\x12\x1b\n" +
	"\x06useRTH\x18\a \x01(\bH\x06R\x06useRTH\x88\x01\x01\x12#\n" +
	"\n" +
	"ignoreSize\x18\b \x01(\bH\aR\n" +
	"ignoreSize\x88\x01\x01\x12S\n" +
	"\vmiscOptions\x18\t \x03(\v21.protobuf.HistoricalTicksRequest.MiscOptionsEntryR\vmiscOptions\x1a>\n" +
	"\x10MiscOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_contractB\x10\n" +
	"\x0e_startDateTimeB\x0e\n" +
	"\f_endDateTimeB\x10\n" +
	"\x0e_numberOfTicksB\r\n" +
	"\v_whatToShowB\t\n" +
	"\a_useRTHB\r\n" +
	"\v_ignoreSizeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalTicksRequest_proto_rawDescOnce sync.Once
	file_HistoricalTicksRequest_proto_rawDescData []byte
)

func file_HistoricalTicksRequest_proto_rawDescGZIP() []byte {
	file_HistoricalTicksRequest_proto_rawDescOnce.Do(func() {
		file_HistoricalTicksRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalTicksRequest_proto_rawDesc), len(file_HistoricalTicksRequest_proto_rawDesc)))
	})
	return file_HistoricalTicksRequest_proto_rawDescData
}

var file_HistoricalTicksRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HistoricalTicksRequest_proto_goTypes = []any{
	(*HistoricalTicksRequest)(nil), // 0: protobuf.HistoricalTicksRequest
	nil,                            // 1: protobuf.HistoricalTicksRequest.MiscOptionsEntry
	(*Contract)(nil),               // 2: protobuf.Contract
}
var file_HistoricalTicksRequest_proto_depIdxs = []int32{
	2, // 0: protobuf.HistoricalTicksRequest.contract:type_name -> protobuf.Contract
	1, // 1: protobuf.HistoricalTicksRequest.miscOptions:type_name -> protobuf.HistoricalTicksRequest.MiscOptionsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_HistoricalTicksRequest_proto_init() }
func file_HistoricalTicksRequest_proto_init() {
	if File_HistoricalTicksRequest_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_HistoricalTicksRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalTicksRequest_proto_rawDesc), len(file_HistoricalTicksRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalTicksRequest_proto_goTypes,
		DependencyIndexes: file_HistoricalTicksRequest_proto_depIdxs,
		MessageInfos:      file_HistoricalTicksRequest_proto_msgTypes,
	}.Build()
	File_HistoricalTicksRequest_proto = out.File
	file_HistoricalTicksRequest_proto_goTypes = nil
	file_HistoricalTicksRequest_proto_depIdxs = nil
}
