// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalNewsRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalNewsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReqId                 *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	ConId                 *int32                 `protobuf:"varint,2,opt,name=conId,proto3,oneof" json:"conId,omitempty"`
	ProviderCodes         *string                `protobuf:"bytes,3,opt,name=providerCodes,proto3,oneof" json:"providerCodes,omitempty"`
	StartDateTime         *string                `protobuf:"bytes,4,opt,name=startDateTime,proto3,oneof" json:"startDateTime,omitempty"`
	EndDateTime           *string                `protobuf:"bytes,5,opt,name=endDateTime,proto3,oneof" json:"endDateTime,omitempty"`
	TotalResults          *int32                 `protobuf:"varint,6,opt,name=totalResults,proto3,oneof" json:"totalResults,omitempty"`
	HistoricalNewsOptions map[string]string      `protobuf:"bytes,7,rep,name=historicalNewsOptions,proto3" json:"historicalNewsOptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HistoricalNewsRequest) Reset() {
	*x = HistoricalNewsRequest{}
	mi := &file_HistoricalNewsRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalNewsRequest) ProtoMessage() {}

func (x *HistoricalNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalNewsRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalNewsRequest.ProtoReflect.Descriptor instead.
func (*HistoricalNewsRequest) Descriptor() ([]byte, []int) {
	return file_HistoricalNewsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalNewsRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HistoricalNewsRequest) GetConId() int32 {
	if x != nil && x.ConId != nil {
		return *x.ConId
	}
	return 0
}

func (x *HistoricalNewsRequest) GetProviderCodes() string {
	if x != nil && x.ProviderCodes != nil {
		return *x.ProviderCodes
	}
	return ""
}

func (x *HistoricalNewsRequest) GetStartDateTime() string {
	if x != nil && x.StartDateTime != nil {
		return *x.StartDateTime
	}
	return ""
}

func (x *HistoricalNewsRequest) GetEndDateTime() string {
	if x != nil && x.EndDateTime != nil {
		return *x.EndDateTime
	}
	return ""
}

func (x *HistoricalNewsRequest) GetTotalResults() int32 {
	if x != nil && x.TotalResults != nil {
		return *x.TotalResults
	}
	return 0
}

func (x *HistoricalNewsRequest) GetHistoricalNewsOptions() map[string]string {
	if x != nil {
		return x.HistoricalNewsOptions
	}
	return nil
}

var File_HistoricalNewsRequest_proto protoreflect.FileDescriptor

const file_HistoricalNewsRequest_proto_rawDesc = "" +
	"\n" +
	"\x1bHistoricalNewsRequest.proto\x12\bprotobuf\"\x88\x04\n" +
	"\x15HistoricalNewsRequest\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12\x19\n" +
	"\x05conId\x18\x02 \x01(\x05H\x01R\x05conId\x88\x01\x01\x12)\n" +
	"\rproviderCodes\x18\x03 \x01(\tH\x02R\rproviderCodes\x88\x01\x01\x12)\n" +
	"\rstartDateTime\x18\x04 \x01(\tH\x03R\rstartDateTime\x88\x01\x01\x12%\n" +
	"\vendDateTime\x18\x05 \x01(\tH\x04R\vendDateTime\x88\x01\x01\x12'\n" +
	"\ftotalResults\x18\x06 \x01(\x05H\x05R\ftotalResults\x88\x01\x01\x12p\n" +
	"\x15historicalNewsOptions\x18\a \x03(\v2:.protobuf.HistoricalNewsRequest.HistoricalNewsOptionsEntryR\x15historicalNewsOptions\x1aH\n" +
	"\x1aHistoricalNewsOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_reqIdB\b\n" +
	"\x06_conIdB\x10\n" +
	"\x0e_providerCodesB\x10\n" +
	"\x0e_startDateTimeB\x0e\n" +
	"\f_endDateTimeB\x0f\n" +
	"\r_totalResultsB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalNewsRequest_proto_rawDescOnce sync.Once
	file_HistoricalNewsRequest_proto_rawDescData []byte
)

func file_HistoricalNewsRequest_proto_rawDescGZIP() []byte {
	file_HistoricalNewsRequest_proto_rawDescOnce.Do(func() {
		file_HistoricalNewsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalNewsRequest_proto_rawDesc), len(file_HistoricalNewsRequest_proto_rawDesc)))
	})
	return file_HistoricalNewsRequest_proto_rawDescData
}

var file_HistoricalNewsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HistoricalNewsRequest_proto_goTypes = []any{
	(*HistoricalNewsRequest)(nil), // 0: protobuf.HistoricalNewsRequest
	nil,                           // 1: protobuf.HistoricalNewsRequest.HistoricalNewsOptionsEntry
}
var file_HistoricalNewsRequest_proto_depIdxs = []int32{
	1, // 0: protobuf.HistoricalNewsRequest.historicalNewsOptions:type_name -> protobuf.HistoricalNewsRequest.HistoricalNewsOptionsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_HistoricalNewsRequest_proto_init() }
func file_HistoricalNewsRequest_proto_init() {
	if File_HistoricalNewsRequest_proto != nil {
		return
	}
	file_HistoricalNewsRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalNewsRequest_proto_rawDesc), len(file_HistoricalNewsRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalNewsRequest_proto_goTypes,
		DependencyIndexes: file_HistoricalNewsRequest_proto_depIdxs,
		MessageInfos:      file_HistoricalNewsRequest_proto_msgTypes,
	}.Build()
	File_HistoricalNewsRequest_proto = out.File
	file_HistoricalNewsRequest_proto_goTypes = nil
	file_HistoricalNewsRequest_proto_depIdxs = nil
}
