// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalDataEnd.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalDataEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	StartDateStr  *string                `protobuf:"bytes,2,opt,name=startDateStr,proto3,oneof" json:"startDateStr,omitempty"`
	EndDateStr    *string                `protobuf:"bytes,3,opt,name=endDateStr,proto3,oneof" json:"endDateStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalDataEnd) Reset() {
	*x = HistoricalDataEnd{}
	mi := &file_HistoricalDataEnd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalDataEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalDataEnd) ProtoMessage() {}

func (x *HistoricalDataEnd) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalDataEnd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalDataEnd.ProtoReflect.Descriptor instead.
func (*HistoricalDataEnd) Descriptor() ([]byte, []int) {
	return file_HistoricalDataEnd_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalDataEnd) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HistoricalDataEnd) GetStartDateStr() string {
	if x != nil && x.StartDateStr != nil {
		return *x.StartDateStr
	}
	return ""
}

func (x *HistoricalDataEnd) GetEndDateStr() string {
	if x != nil && x.EndDateStr != nil {
		return *x.EndDateStr
	}
	return ""
}

var File_HistoricalDataEnd_proto protoreflect.FileDescriptor

const file_HistoricalDataEnd_proto_rawDesc = "" +
	"\n" +
	"\x17HistoricalDataEnd.proto\x12\bprotobuf\"\xa6\x01\n" +
	"\x11HistoricalDataEnd\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12'\n" +
	"\fstartDateStr\x18\x02 \x01(\tH\x01R\fstartDateStr\x88\x01\x01\x12#\n" +
	"\n" +
	"endDateStr\x18\x03 \x01(\tH\x02R\n" +
	"endDateStr\x88\x01\x01B\b\n" +
	"\x06_reqIdB\x0f\n" +
	"\r_startDateStrB\r\n" +
	"\v_endDateStrB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalDataEnd_proto_rawDescOnce sync.Once
	file_HistoricalDataEnd_proto_rawDescData []byte
)

func file_HistoricalDataEnd_proto_rawDescGZIP() []byte {
	file_HistoricalDataEnd_proto_rawDescOnce.Do(func() {
		file_HistoricalDataEnd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalDataEnd_proto_rawDesc), len(file_HistoricalDataEnd_proto_rawDesc)))
	})
	return file_HistoricalDataEnd_proto_rawDescData
}

var file_HistoricalDataEnd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HistoricalDataEnd_proto_goTypes = []any{
	(*HistoricalDataEnd)(nil), // 0: protobuf.HistoricalDataEnd
}
var file_HistoricalDataEnd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HistoricalDataEnd_proto_init() }
func file_HistoricalDataEnd_proto_init() {
	if File_HistoricalDataEnd_proto != nil {
		return
	}
	file_HistoricalDataEnd_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalDataEnd_proto_rawDesc), len(file_HistoricalDataEnd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalDataEnd_proto_goTypes,
		DependencyIndexes: file_HistoricalDataEnd_proto_depIdxs,
		MessageInfos:      file_HistoricalDataEnd_proto_msgTypes,
	}.Build()
	File_HistoricalDataEnd_proto = out.File
	file_HistoricalDataEnd_proto_goTypes = nil
	file_HistoricalDataEnd_proto_depIdxs = nil
}
