// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalSession.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDateTime *string                `protobuf:"bytes,1,opt,name=startDateTime,proto3,oneof" json:"startDateTime,omitempty"`
	EndDateTime   *string                `protobuf:"bytes,2,opt,name=endDateTime,proto3,oneof" json:"endDateTime,omitempty"`
	RefDate       *string                `protobuf:"bytes,3,opt,name=refDate,proto3,oneof" json:"refDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalSession) Reset() {
	*x = HistoricalSession{}
	mi := &file_HistoricalSession_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalSession) ProtoMessage() {}

func (x *HistoricalSession) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalSession_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalSession.ProtoReflect.Descriptor instead.
func (*HistoricalSession) Descriptor() ([]byte, []int) {
	return file_HistoricalSession_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalSession) GetStartDateTime() string {
	if x != nil && x.StartDateTime != nil {
		return *x.StartDateTime
	}
	return ""
}

func (x *HistoricalSession) GetEndDateTime() string {
	if x != nil && x.EndDateTime != nil {
		return *x.EndDateTime
	}
	return ""
}

func (x *HistoricalSession) GetRefDate() string {
	if x != nil && x.RefDate != nil {
		return *x.RefDate
	}
	return ""
}

var File_HistoricalSession_proto protoreflect.FileDescriptor

const file_HistoricalSession_proto_rawDesc = "" +
	"\n" +
	"\x17HistoricalSession.proto\x12\bprotobuf\"\xb2\x01\n" +
	"\x11HistoricalSession\x12)\n" +
	"\rstartDateTime\x18\x01 \x01(\tH\x00R\rstartDateTime\x88\x01\x01\x12%\n" +
	"\vendDateTime\x18\x02 \x01(\tH\x01R\vendDateTime\x88\x01\x01\x12\x1d\n" +
	"\arefDate\x18\x03 \x01(\tH\x02R\arefDate\x88\x01\x01B\x10\n" +
	"\x0e_startDateTimeB\x0e\n" +
	"\f_endDateTimeB\n" +
	"\n" +
	"\b_refDateB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalSession_proto_rawDescOnce sync.Once
	file_HistoricalSession_proto_rawDescData []byte
)

func file_HistoricalSession_proto_rawDescGZIP() []byte {
	file_HistoricalSession_proto_rawDescOnce.Do(func() {
		file_HistoricalSession_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalSession_proto_rawDesc), len(file_HistoricalSession_proto_rawDesc)))
	})
	return file_HistoricalSession_proto_rawDescData
}

var file_HistoricalSession_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HistoricalSession_proto_goTypes = []any{
	(*HistoricalSession)(nil), // 0: protobuf.HistoricalSession
}
var file_HistoricalSession_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HistoricalSession_proto_init() }
func file_HistoricalSession_proto_init() {
	if File_HistoricalSession_proto != nil {
		return
	}
	file_HistoricalSession_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalSession_proto_rawDesc), len(file_HistoricalSession_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalSession_proto_goTypes,
		DependencyIndexes: file_HistoricalSession_proto_depIdxs,
		MessageInfos:      file_HistoricalSession_proto_msgTypes,
	}.Build()
	File_HistoricalSession_proto = out.File
	file_HistoricalSession_proto_goTypes = nil
	file_HistoricalSession_proto_depIdxs = nil
}
