// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalNews.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalNews struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Time          *string                `protobuf:"bytes,2,opt,name=time,proto3,oneof" json:"time,omitempty"`
	ProviderCode  *string                `protobuf:"bytes,3,opt,name=providerCode,proto3,oneof" json:"providerCode,omitempty"`
	ArticleId     *string                `protobuf:"bytes,4,opt,name=articleId,proto3,oneof" json:"articleId,omitempty"`
	Headline      *string                `protobuf:"bytes,5,opt,name=headline,proto3,oneof" json:"headline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalNews) Reset() {
	*x = HistoricalNews{}
	mi := &file_HistoricalNews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalNews) ProtoMessage() {}

func (x *HistoricalNews) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalNews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalNews.ProtoReflect.Descriptor instead.
func (*HistoricalNews) Descriptor() ([]byte, []int) {
	return file_HistoricalNews_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalNews) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HistoricalNews) GetTime() string {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return ""
}

func (x *HistoricalNews) GetProviderCode() string {
	if x != nil && x.ProviderCode != nil {
		return *x.ProviderCode
	}
	return ""
}

func (x *HistoricalNews) GetArticleId() string {
	if x != nil && x.ArticleId != nil {
		return *x.ArticleId
	}
	return ""
}

func (x *HistoricalNews) GetHeadline() string {
	if x != nil && x.Headline != nil {
		return *x.Headline
	}
	return ""
}

var File_HistoricalNews_proto protoreflect.FileDescriptor

const file_HistoricalNews_proto_rawDesc = "" +
	"\n" +
	"\x14HistoricalNews.proto\x12\bprotobuf\"\xf0\x01\n" +
	"\x0eHistoricalNews\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\x02 \x01(\tH\x01R\x04time\x88\x01\x01\x12'\n" +
	"\fproviderCode\x18\x03 \x01(\tH\x02R\fproviderCode\x88\x01\x01\x12!\n" +
	"\tarticleId\x18\x04 \x01(\tH\x03R\tarticleId\x88\x01\x01\x12\x1f\n" +
	"\bheadline\x18\x05 \x01(\tH\x04R\bheadline\x88\x01\x01B\b\n" +
	"\x06_reqIdB\a\n" +
	"\x05_timeB\x0f\n" +
	"\r_providerCodeB\f\n" +
	"\n" +
	"_articleIdB\v\n" +
	"\t_headlineB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalNews_proto_rawDescOnce sync.Once
	file_HistoricalNews_proto_rawDescData []byte
)

func file_HistoricalNews_proto_rawDescGZIP() []byte {
	file_HistoricalNews_proto_rawDescOnce.Do(func() {
		file_HistoricalNews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalNews_proto_rawDesc), len(file_HistoricalNews_proto_rawDesc)))
	})
	return file_HistoricalNews_proto_rawDescData
}

var file_HistoricalNews_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HistoricalNews_proto_goTypes = []any{
	(*HistoricalNews)(nil), // 0: protobuf.HistoricalNews
}
var file_HistoricalNews_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HistoricalNews_proto_init() }
func file_HistoricalNews_proto_init() {
	if File_HistoricalNews_proto != nil {
		return
	}
	file_HistoricalNews_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalNews_proto_rawDesc), len(file_HistoricalNews_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalNews_proto_goTypes,
		DependencyIndexes: file_HistoricalNews_proto_depIdxs,
		MessageInfos:      file_HistoricalNews_proto_msgTypes,
	}.Build()
	File_HistoricalNews_proto = out.File
	file_HistoricalNews_proto_goTypes = nil
	file_HistoricalNews_proto_depIdxs = nil
}
