// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalDataBar.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalDataBar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *string                `protobuf:"bytes,1,opt,name=date,proto3,oneof" json:"date,omitempty"`
	Open          *float64               `protobuf:"fixed64,2,opt,name=open,proto3,oneof" json:"open,omitempty"`
	High          *float64               `protobuf:"fixed64,3,opt,name=high,proto3,oneof" json:"high,omitempty"`
	Low           *float64               `protobuf:"fixed64,4,opt,name=low,proto3,oneof" json:"low,omitempty"`
	Close         *float64               `protobuf:"fixed64,5,opt,name=close,proto3,oneof" json:"close,omitempty"`
	Volume        *string                `protobuf:"bytes,6,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	WAP           *string                `protobuf:"bytes,7,opt,name=WAP,proto3,oneof" json:"WAP,omitempty"`
	BarCount      *int32                 `protobuf:"varint,8,opt,name=barCount,proto3,oneof" json:"barCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalDataBar) Reset() {
	*x = HistoricalDataBar{}
	mi := &file_HistoricalDataBar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalDataBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalDataBar) ProtoMessage() {}

func (x *HistoricalDataBar) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalDataBar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalDataBar.ProtoReflect.Descriptor instead.
func (*HistoricalDataBar) Descriptor() ([]byte, []int) {
	return file_HistoricalDataBar_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalDataBar) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *HistoricalDataBar) GetOpen() float64 {
	if x != nil && x.Open != nil {
		return *x.Open
	}
	return 0
}

func (x *HistoricalDataBar) GetHigh() float64 {
	if x != nil && x.High != nil {
		return *x.High
	}
	return 0
}

func (x *HistoricalDataBar) GetLow() float64 {
	if x != nil && x.Low != nil {
		return *x.Low
	}
	return 0
}

func (x *HistoricalDataBar) GetClose() float64 {
	if x != nil && x.Close != nil {
		return *x.Close
	}
	return 0
}

func (x *HistoricalDataBar) GetVolume() string {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return ""
}

func (x *HistoricalDataBar) GetWAP() string {
	if x != nil && x.WAP != nil {
		return *x.WAP
	}
	return ""
}

func (x *HistoricalDataBar) GetBarCount() int32 {
	if x != nil && x.BarCount != nil {
		return *x.BarCount
	}
	return 0
}

var File_HistoricalDataBar_proto protoreflect.FileDescriptor

const file_HistoricalDataBar_proto_rawDesc = "" +
	"\n" +
	"\x17HistoricalDataBar.proto\x12\bprotobuf\"\xb2\x02\n" +
	"\x11HistoricalDataBar\x12\x17\n" +
	"\x04date\x18\x01 \x01(\tH\x00R\x04date\x88\x01\x01\x12\x17\n" +
	"\x04open\x18\x02 \x01(\x01H\x01R\x04open\x88\x01\x01\x12\x17\n" +
	"\x04high\x18\x03 \x01(\x01H\x02R\x04high\x88\x01\x01\x12\x15\n" +
	"\x03low\x18\x04 \x01(\x01H\x03R\x03low\x88\x01\x01\x12\x19\n" +
	"\x05close\x18\x05 \x01(\x01H\x04R\x05close\x88\x01\x01\x12\x1b\n" +
	"\x06volume\x18\x06 \x01(\tH\x05R\x06volume\x88\x01\x01\x12\x15\n" +
	"\x03WAP\x18\a \x01(\tH\x06R\x03WAP\x88\x01\x01\x12\x1f\n" +
	"\bbarCount\x18\b \x01(\x05H\aR\bbarCount\x88\x01\x01B\a\n" +
	"\x05_dateB\a\n" +
	"\x05_openB\a\n" +
	"\x05_highB\x06\n" +
	"\x04_lowB\b\n" +
	"\x06_closeB\t\n" +
	"\a_volumeB\x06\n" +
	"\x04_WAPB\v\n" +
	"\t_barCountB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalDataBar_proto_rawDescOnce sync.Once
	file_HistoricalDataBar_proto_rawDescData []byte
)

func file_HistoricalDataBar_proto_rawDescGZIP() []byte {
	file_HistoricalDataBar_proto_rawDescOnce.Do(func() {
		file_HistoricalDataBar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalDataBar_proto_rawDesc), len(file_HistoricalDataBar_proto_rawDesc)))
	})
	return file_HistoricalDataBar_proto_rawDescData
}

var file_HistoricalDataBar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HistoricalDataBar_proto_goTypes = []any{
	(*HistoricalDataBar)(nil), // 0: protobuf.HistoricalDataBar
}
var file_HistoricalDataBar_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HistoricalDataBar_proto_init() }
func file_HistoricalDataBar_proto_init() {
	if File_HistoricalDataBar_proto != nil {
		return
	}
	file_HistoricalDataBar_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalDataBar_proto_rawDesc), len(file_HistoricalDataBar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalDataBar_proto_goTypes,
		DependencyIndexes: file_HistoricalDataBar_proto_depIdxs,
		MessageInfos:      file_HistoricalDataBar_proto_msgTypes,
	}.Build()
	File_HistoricalDataBar_proto = out.File
	file_HistoricalDataBar_proto_goTypes = nil
	file_HistoricalDataBar_proto_depIdxs = nil
}
