// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: HistogramDataRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistogramDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Contract      *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	UseRTH        *bool                  `protobuf:"varint,3,opt,name=useRTH,proto3,oneof" json:"useRTH,omitempty"`
	TimePeriod    *string                `protobuf:"bytes,4,opt,name=timePeriod,proto3,oneof" json:"timePeriod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramDataRequest) Reset() {
	*x = HistogramDataRequest{}
	mi := &file_HistogramDataRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramDataRequest) ProtoMessage() {}

func (x *HistogramDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HistogramDataRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramDataRequest.ProtoReflect.Descriptor instead.
func (*HistogramDataRequest) Descriptor() ([]byte, []int) {
	return file_HistogramDataRequest_proto_rawDescGZIP(), []int{0}
}

func (x *HistogramDataRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HistogramDataRequest) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *HistogramDataRequest) GetUseRTH() bool {
	if x != nil && x.UseRTH != nil {
		return *x.UseRTH
	}
	return false
}

func (x *HistogramDataRequest) GetTimePeriod() string {
	if x != nil && x.TimePeriod != nil {
		return *x.TimePeriod
	}
	return ""
}

var File_HistogramDataRequest_proto protoreflect.FileDescriptor

var file_HistogramDataRequest_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01, 0x0a, 0x14, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x48, 0x01, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x52, 0x54, 0x48, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x02, 0x52, 0x06, 0x75, 0x73, 0x65, 0x52, 0x54, 0x48, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x03, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x65, 0x71, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75, 0x73, 0x65,
	0x52, 0x54, 0x48, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_HistogramDataRequest_proto_rawDescOnce sync.Once
	file_HistogramDataRequest_proto_rawDescData []byte
)

func file_HistogramDataRequest_proto_rawDescGZIP() []byte {
	file_HistogramDataRequest_proto_rawDescOnce.Do(func() {
		file_HistogramDataRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistogramDataRequest_proto_rawDesc), len(file_HistogramDataRequest_proto_rawDesc)))
	})
	return file_HistogramDataRequest_proto_rawDescData
}

var file_HistogramDataRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HistogramDataRequest_proto_goTypes = []any{
	(*HistogramDataRequest)(nil), // 0: protobuf.HistogramDataRequest
	(*Contract)(nil),             // 1: protobuf.Contract
}
var file_HistogramDataRequest_proto_depIdxs = []int32{
	1, // 0: protobuf.HistogramDataRequest.contract:type_name -> protobuf.Contract
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_HistogramDataRequest_proto_init() }
func file_HistogramDataRequest_proto_init() {
	if File_HistogramDataRequest_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_HistogramDataRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistogramDataRequest_proto_rawDesc), len(file_HistogramDataRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistogramDataRequest_proto_goTypes,
		DependencyIndexes: file_HistogramDataRequest_proto_depIdxs,
		MessageInfos:      file_HistogramDataRequest_proto_msgTypes,
	}.Build()
	File_HistogramDataRequest_proto = out.File
	file_HistogramDataRequest_proto_goTypes = nil
	file_HistogramDataRequest_proto_depIdxs = nil
}
