// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalDataRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReqId          *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Contract       *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	EndDateTime    *string                `protobuf:"bytes,3,opt,name=endDateTime,proto3,oneof" json:"endDateTime,omitempty"`
	BarSizeSetting *string                `protobuf:"bytes,4,opt,name=barSizeSetting,proto3,oneof" json:"barSizeSetting,omitempty"`
	Duration       *string                `protobuf:"bytes,5,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	UseRTH         *bool                  `protobuf:"varint,6,opt,name=useRTH,proto3,oneof" json:"useRTH,omitempty"`
	WhatToShow     *string                `protobuf:"bytes,7,opt,name=whatToShow,proto3,oneof" json:"whatToShow,omitempty"`
	FormatDate     *int32                 `protobuf:"varint,8,opt,name=formatDate,proto3,oneof" json:"formatDate,omitempty"`
	KeepUpToDate   *bool                  `protobuf:"varint,9,opt,name=keepUpToDate,proto3,oneof" json:"keepUpToDate,omitempty"`
	ChartOptions   map[string]string      `protobuf:"bytes,10,rep,name=chartOptions,proto3" json:"chartOptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HistoricalDataRequest) Reset() {
	*x = HistoricalDataRequest{}
	mi := &file_HistoricalDataRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalDataRequest) ProtoMessage() {}

func (x *HistoricalDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalDataRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalDataRequest.ProtoReflect.Descriptor instead.
func (*HistoricalDataRequest) Descriptor() ([]byte, []int) {
	return file_HistoricalDataRequest_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalDataRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HistoricalDataRequest) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *HistoricalDataRequest) GetEndDateTime() string {
	if x != nil && x.EndDateTime != nil {
		return *x.EndDateTime
	}
	return ""
}

func (x *HistoricalDataRequest) GetBarSizeSetting() string {
	if x != nil && x.BarSizeSetting != nil {
		return *x.BarSizeSetting
	}
	return ""
}

func (x *HistoricalDataRequest) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *HistoricalDataRequest) GetUseRTH() bool {
	if x != nil && x.UseRTH != nil {
		return *x.UseRTH
	}
	return false
}

func (x *HistoricalDataRequest) GetWhatToShow() string {
	if x != nil && x.WhatToShow != nil {
		return *x.WhatToShow
	}
	return ""
}

func (x *HistoricalDataRequest) GetFormatDate() int32 {
	if x != nil && x.FormatDate != nil {
		return *x.FormatDate
	}
	return 0
}

func (x *HistoricalDataRequest) GetKeepUpToDate() bool {
	if x != nil && x.KeepUpToDate != nil {
		return *x.KeepUpToDate
	}
	return false
}

func (x *HistoricalDataRequest) GetChartOptions() map[string]string {
	if x != nil {
		return x.ChartOptions
	}
	return nil
}

var File_HistoricalDataRequest_proto protoreflect.FileDescriptor

const file_HistoricalDataRequest_proto_rawDesc = "" +
	"\n" +
	"\x1bHistoricalDataRequest.proto\x12\bprotobuf\x1a\x0eContract.proto\"\x85\x05\n" +
	"\x15HistoricalDataRequest\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x12.protobuf.ContractH\x01R\bcontract\x88\x01\x01\x12%\n" +
	"\vendDateTime\x18\x03 \x01(\tH\x02R\vendDateTime\x88\x01\x01\x12+\n" +
	"\x0ebarSizeSetting\x18\x04 \x01(\tH\x03R\x0ebarSizeSetting\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\x05 \x01(\tH\x04R\bduration\x88\x01\x01\x12\x1b\n" +
	"\x06useRTH\x18\x06 \x01(\bH\x05R\x06useRTH\x88\x01\x01\x12#\n" +
	"\n" +
	"whatToShow\x18\a \x01(\tH\x06R\n" +
	"whatToShow\x88\x01\x01\x12#\n" +
	"\n" +
	"formatDate\x18\b \x01(\x05H\aR\n" +
	"formatDate\x88\x01\x01\x12'\n" +
	"\fkeepUpToDate\x18\t \x01(\bH\bR\fkeepUpToDate\x88\x01\x01\x12U\n" +
	"\fchartOptions\x18\n" +
	" \x03(\v21.protobuf.HistoricalDataRequest.ChartOptionsEntryR\fchartOptions\x1a?\n" +
	"\x11ChartOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_contractB\x0e\n" +
	"\f_endDateTimeB\x11\n" +
	"\x0f_barSizeSettingB\v\n" +
	"\t_durationB\t\n" +
	"\a_useRTHB\r\n" +
	"\v_whatToShowB\r\n" +
	"\v_formatDateB\x0f\n" +
	"\r_keepUpToDateB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalDataRequest_proto_rawDescOnce sync.Once
	file_HistoricalDataRequest_proto_rawDescData []byte
)

func file_HistoricalDataRequest_proto_rawDescGZIP() []byte {
	file_HistoricalDataRequest_proto_rawDescOnce.Do(func() {
		file_HistoricalDataRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalDataRequest_proto_rawDesc), len(file_HistoricalDataRequest_proto_rawDesc)))
	})
	return file_HistoricalDataRequest_proto_rawDescData
}

var file_HistoricalDataRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HistoricalDataRequest_proto_goTypes = []any{
	(*HistoricalDataRequest)(nil), // 0: protobuf.HistoricalDataRequest
	nil,                           // 1: protobuf.HistoricalDataRequest.ChartOptionsEntry
	(*Contract)(nil),              // 2: protobuf.Contract
}
var file_HistoricalDataRequest_proto_depIdxs = []int32{
	2, // 0: protobuf.HistoricalDataRequest.contract:type_name -> protobuf.Contract
	1, // 1: protobuf.HistoricalDataRequest.chartOptions:type_name -> protobuf.HistoricalDataRequest.ChartOptionsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_HistoricalDataRequest_proto_init() }
func file_HistoricalDataRequest_proto_init() {
	if File_HistoricalDataRequest_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_HistoricalDataRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalDataRequest_proto_rawDesc), len(file_HistoricalDataRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalDataRequest_proto_goTypes,
		DependencyIndexes: file_HistoricalDataRequest_proto_depIdxs,
		MessageInfos:      file_HistoricalDataRequest_proto_msgTypes,
	}.Build()
	File_HistoricalDataRequest_proto = out.File
	file_HistoricalDataRequest_proto_goTypes = nil
	file_HistoricalDataRequest_proto_depIdxs = nil
}
