// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: HistoricalTicksBidAsk.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalTicksBidAsk struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	ReqId                 *int32                  `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	HistoricalTicksBidAsk []*HistoricalTickBidAsk `protobuf:"bytes,2,rep,name=historicalTicksBidAsk,proto3" json:"historicalTicksBidAsk,omitempty"`
	IsDone                *bool                   `protobuf:"varint,3,opt,name=isDone,proto3,oneof" json:"isDone,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HistoricalTicksBidAsk) Reset() {
	*x = HistoricalTicksBidAsk{}
	mi := &file_HistoricalTicksBidAsk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalTicksBidAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalTicksBidAsk) ProtoMessage() {}

func (x *HistoricalTicksBidAsk) ProtoReflect() protoreflect.Message {
	mi := &file_HistoricalTicksBidAsk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalTicksBidAsk.ProtoReflect.Descriptor instead.
func (*HistoricalTicksBidAsk) Descriptor() ([]byte, []int) {
	return file_HistoricalTicksBidAsk_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalTicksBidAsk) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HistoricalTicksBidAsk) GetHistoricalTicksBidAsk() []*HistoricalTickBidAsk {
	if x != nil {
		return x.HistoricalTicksBidAsk
	}
	return nil
}

func (x *HistoricalTicksBidAsk) GetIsDone() bool {
	if x != nil && x.IsDone != nil {
		return *x.IsDone
	}
	return false
}

var File_HistoricalTicksBidAsk_proto protoreflect.FileDescriptor

const file_HistoricalTicksBidAsk_proto_rawDesc = "" +
	"\n" +
	"\x1bHistoricalTicksBidAsk.proto\x12\bprotobuf\x1a\x1aHistoricalTickBidAsk.proto\"\xba\x01\n" +
	"\x15HistoricalTicksBidAsk\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12T\n" +
	"\x15historicalTicksBidAsk\x18\x02 \x03(\v2\x1e.protobuf.HistoricalTickBidAskR\x15historicalTicksBidAsk\x12\x1b\n" +
	"\x06isDone\x18\x03 \x01(\bH\x01R\x06isDone\x88\x01\x01B\b\n" +
	"\x06_reqIdB\t\n" +
	"\a_isDoneB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_HistoricalTicksBidAsk_proto_rawDescOnce sync.Once
	file_HistoricalTicksBidAsk_proto_rawDescData []byte
)

func file_HistoricalTicksBidAsk_proto_rawDescGZIP() []byte {
	file_HistoricalTicksBidAsk_proto_rawDescOnce.Do(func() {
		file_HistoricalTicksBidAsk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_HistoricalTicksBidAsk_proto_rawDesc), len(file_HistoricalTicksBidAsk_proto_rawDesc)))
	})
	return file_HistoricalTicksBidAsk_proto_rawDescData
}

var file_HistoricalTicksBidAsk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HistoricalTicksBidAsk_proto_goTypes = []any{
	(*HistoricalTicksBidAsk)(nil), // 0: protobuf.HistoricalTicksBidAsk
	(*HistoricalTickBidAsk)(nil),  // 1: protobuf.HistoricalTickBidAsk
}
var file_HistoricalTicksBidAsk_proto_depIdxs = []int32{
	1, // 0: protobuf.HistoricalTicksBidAsk.historicalTicksBidAsk:type_name -> protobuf.HistoricalTickBidAsk
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_HistoricalTicksBidAsk_proto_init() }
func file_HistoricalTicksBidAsk_proto_init() {
	if File_HistoricalTicksBidAsk_proto != nil {
		return
	}
	file_HistoricalTickBidAsk_proto_init()
	file_HistoricalTicksBidAsk_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_HistoricalTicksBidAsk_proto_rawDesc), len(file_HistoricalTicksBidAsk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoricalTicksBidAsk_proto_goTypes,
		DependencyIndexes: file_HistoricalTicksBidAsk_proto_depIdxs,
		MessageInfos:      file_HistoricalTicksBidAsk_proto_msgTypes,
	}.Build()
	File_HistoricalTicksBidAsk_proto = out.File
	file_HistoricalTicksBidAsk_proto_goTypes = nil
	file_HistoricalTicksBidAsk_proto_depIdxs = nil
}
