// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: IdsRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumIds        *int32                 `protobuf:"varint,1,opt,name=numIds,proto3,oneof" json:"numIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdsRequest) Reset() {
	*x = IdsRequest{}
	mi := &file_IdsRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdsRequest) ProtoMessage() {}

func (x *IdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IdsRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdsRequest.ProtoReflect.Descriptor instead.
func (*IdsRequest) Descriptor() ([]byte, []int) {
	return file_IdsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *IdsRequest) GetNumIds() int32 {
	if x != nil && x.NumIds != nil {
		return *x.NumIds
	}
	return 0
}

var File_IdsRequest_proto protoreflect.FileDescriptor

var file_IdsRequest_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x34, 0x0a, 0x0a,
	0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x49, 0x64, 0x73, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6e, 0x75, 0x6d, 0x49,
	0x64, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_IdsRequest_proto_rawDescOnce sync.Once
	file_IdsRequest_proto_rawDescData []byte
)

func file_IdsRequest_proto_rawDescGZIP() []byte {
	file_IdsRequest_proto_rawDescOnce.Do(func() {
		file_IdsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_IdsRequest_proto_rawDesc), len(file_IdsRequest_proto_rawDesc)))
	})
	return file_IdsRequest_proto_rawDescData
}

var file_IdsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_IdsRequest_proto_goTypes = []any{
	(*IdsRequest)(nil), // 0: protobuf.IdsRequest
}
var file_IdsRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_IdsRequest_proto_init() }
func file_IdsRequest_proto_init() {
	if File_IdsRequest_proto != nil {
		return
	}
	file_IdsRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_IdsRequest_proto_rawDesc), len(file_IdsRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IdsRequest_proto_goTypes,
		DependencyIndexes: file_IdsRequest_proto_depIdxs,
		MessageInfos:      file_IdsRequest_proto_msgTypes,
	}.Build()
	File_IdsRequest_proto = out.File
	file_IdsRequest_proto_goTypes = nil
	file_IdsRequest_proto_depIdxs = nil
}
