// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: LockAndExitConfig.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockAndExitConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AutoLogoffTime   *string                `protobuf:"bytes,1,opt,name=autoLogoffTime,proto3,oneof" json:"autoLogoffTime,omitempty"`
	AutoLogoffPeriod *string                `protobuf:"bytes,2,opt,name=autoLogoffPeriod,proto3,oneof" json:"autoLogoffPeriod,omitempty"`
	AutoLogoffType   *string                `protobuf:"bytes,3,opt,name=autoLogoffType,proto3,oneof" json:"autoLogoffType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LockAndExitConfig) Reset() {
	*x = LockAndExitConfig{}
	mi := &file_LockAndExitConfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAndExitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAndExitConfig) ProtoMessage() {}

func (x *LockAndExitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_LockAndExitConfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAndExitConfig.ProtoReflect.Descriptor instead.
func (*LockAndExitConfig) Descriptor() ([]byte, []int) {
	return file_LockAndExitConfig_proto_rawDescGZIP(), []int{0}
}

func (x *LockAndExitConfig) GetAutoLogoffTime() string {
	if x != nil && x.AutoLogoffTime != nil {
		return *x.AutoLogoffTime
	}
	return ""
}

func (x *LockAndExitConfig) GetAutoLogoffPeriod() string {
	if x != nil && x.AutoLogoffPeriod != nil {
		return *x.AutoLogoffPeriod
	}
	return ""
}

func (x *LockAndExitConfig) GetAutoLogoffType() string {
	if x != nil && x.AutoLogoffType != nil {
		return *x.AutoLogoffType
	}
	return ""
}

var File_LockAndExitConfig_proto protoreflect.FileDescriptor

const file_LockAndExitConfig_proto_rawDesc = "" +
	"\n" +
	"\x17LockAndExitConfig.proto\x12\bprotobuf\"\xd9\x01\n" +
	"\x11LockAndExitConfig\x12+\n" +
	"\x0eautoLogoffTime\x18\x01 \x01(\tH\x00R\x0eautoLogoffTime\x88\x01\x01\x12/\n" +
	"\x10autoLogoffPeriod\x18\x02 \x01(\tH\x01R\x10autoLogoffPeriod\x88\x01\x01\x12+\n" +
	"\x0eautoLogoffType\x18\x03 \x01(\tH\x02R\x0eautoLogoffType\x88\x01\x01B\x11\n" +
	"\x0f_autoLogoffTimeB\x13\n" +
	"\x11_autoLogoffPeriodB\x11\n" +
	"\x0f_autoLogoffTypeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_LockAndExitConfig_proto_rawDescOnce sync.Once
	file_LockAndExitConfig_proto_rawDescData []byte
)

func file_LockAndExitConfig_proto_rawDescGZIP() []byte {
	file_LockAndExitConfig_proto_rawDescOnce.Do(func() {
		file_LockAndExitConfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_LockAndExitConfig_proto_rawDesc), len(file_LockAndExitConfig_proto_rawDesc)))
	})
	return file_LockAndExitConfig_proto_rawDescData
}

var file_LockAndExitConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_LockAndExitConfig_proto_goTypes = []any{
	(*LockAndExitConfig)(nil), // 0: protobuf.LockAndExitConfig
}
var file_LockAndExitConfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_LockAndExitConfig_proto_init() }
func file_LockAndExitConfig_proto_init() {
	if File_LockAndExitConfig_proto != nil {
		return
	}
	file_LockAndExitConfig_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_LockAndExitConfig_proto_rawDesc), len(file_LockAndExitConfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LockAndExitConfig_proto_goTypes,
		DependencyIndexes: file_LockAndExitConfig_proto_depIdxs,
		MessageInfos:      file_LockAndExitConfig_proto_msgTypes,
	}.Build()
	File_LockAndExitConfig_proto = out.File
	file_LockAndExitConfig_proto_goTypes = nil
	file_LockAndExitConfig_proto_depIdxs = nil
}
