// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: MarketDataTypeRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketDataTypeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketDataType *int32                 `protobuf:"varint,1,opt,name=marketDataType,proto3,oneof" json:"marketDataType,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarketDataTypeRequest) Reset() {
	*x = MarketDataTypeRequest{}
	mi := &file_MarketDataTypeRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataTypeRequest) ProtoMessage() {}

func (x *MarketDataTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MarketDataTypeRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataTypeRequest.ProtoReflect.Descriptor instead.
func (*MarketDataTypeRequest) Descriptor() ([]byte, []int) {
	return file_MarketDataTypeRequest_proto_rawDescGZIP(), []int{0}
}

func (x *MarketDataTypeRequest) GetMarketDataType() int32 {
	if x != nil && x.MarketDataType != nil {
		return *x.MarketDataType
	}
	return 0
}

var File_MarketDataTypeRequest_proto protoreflect.FileDescriptor

const file_MarketDataTypeRequest_proto_rawDesc = "" +
	"\n" +
	"\x1bMarketDataTypeRequest.proto\x12\bprotobuf\"W\n" +
	"\x15MarketDataTypeRequest\x12+\n" +
	"\x0emarketDataType\x18\x01 \x01(\x05H\x00R\x0emarketDataType\x88\x01\x01B\x11\n" +
	"\x0f_marketDataTypeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_MarketDataTypeRequest_proto_rawDescOnce sync.Once
	file_MarketDataTypeRequest_proto_rawDescData []byte
)

func file_MarketDataTypeRequest_proto_rawDescGZIP() []byte {
	file_MarketDataTypeRequest_proto_rawDescOnce.Do(func() {
		file_MarketDataTypeRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MarketDataTypeRequest_proto_rawDesc), len(file_MarketDataTypeRequest_proto_rawDesc)))
	})
	return file_MarketDataTypeRequest_proto_rawDescData
}

var file_MarketDataTypeRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MarketDataTypeRequest_proto_goTypes = []any{
	(*MarketDataTypeRequest)(nil), // 0: protobuf.MarketDataTypeRequest
}
var file_MarketDataTypeRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MarketDataTypeRequest_proto_init() }
func file_MarketDataTypeRequest_proto_init() {
	if File_MarketDataTypeRequest_proto != nil {
		return
	}
	file_MarketDataTypeRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MarketDataTypeRequest_proto_rawDesc), len(file_MarketDataTypeRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MarketDataTypeRequest_proto_goTypes,
		DependencyIndexes: file_MarketDataTypeRequest_proto_depIdxs,
		MessageInfos:      file_MarketDataTypeRequest_proto_msgTypes,
	}.Build()
	File_MarketDataTypeRequest_proto = out.File
	file_MarketDataTypeRequest_proto_goTypes = nil
	file_MarketDataTypeRequest_proto_depIdxs = nil
}
