// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: MessageConfig.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	DefaultAction *string                `protobuf:"bytes,4,opt,name=defaultAction,proto3,oneof" json:"defaultAction,omitempty"`
	Enabled       *bool                  `protobuf:"varint,5,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageConfig) Reset() {
	*x = MessageConfig{}
	mi := &file_MessageConfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageConfig) ProtoMessage() {}

func (x *MessageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_MessageConfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageConfig.ProtoReflect.Descriptor instead.
func (*MessageConfig) Descriptor() ([]byte, []int) {
	return file_MessageConfig_proto_rawDescGZIP(), []int{0}
}

func (x *MessageConfig) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MessageConfig) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MessageConfig) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *MessageConfig) GetDefaultAction() string {
	if x != nil && x.DefaultAction != nil {
		return *x.DefaultAction
	}
	return ""
}

func (x *MessageConfig) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

var File_MessageConfig_proto protoreflect.FileDescriptor

const file_MessageConfig_proto_rawDesc = "" +
	"\n" +
	"\x13MessageConfig.proto\x12\bprotobuf\"\xe3\x01\n" +
	"\rMessageConfig\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x02R\amessage\x88\x01\x01\x12)\n" +
	"\rdefaultAction\x18\x04 \x01(\tH\x03R\rdefaultAction\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x05 \x01(\bH\x04R\aenabled\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_messageB\x10\n" +
	"\x0e_defaultActionB\n" +
	"\n" +
	"\b_enabledB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_MessageConfig_proto_rawDescOnce sync.Once
	file_MessageConfig_proto_rawDescData []byte
)

func file_MessageConfig_proto_rawDescGZIP() []byte {
	file_MessageConfig_proto_rawDescOnce.Do(func() {
		file_MessageConfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MessageConfig_proto_rawDesc), len(file_MessageConfig_proto_rawDesc)))
	})
	return file_MessageConfig_proto_rawDescData
}

var file_MessageConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MessageConfig_proto_goTypes = []any{
	(*MessageConfig)(nil), // 0: protobuf.MessageConfig
}
var file_MessageConfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MessageConfig_proto_init() }
func file_MessageConfig_proto_init() {
	if File_MessageConfig_proto != nil {
		return
	}
	file_MessageConfig_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MessageConfig_proto_rawDesc), len(file_MessageConfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MessageConfig_proto_goTypes,
		DependencyIndexes: file_MessageConfig_proto_depIdxs,
		MessageInfos:      file_MessageConfig_proto_msgTypes,
	}.Build()
	File_MessageConfig_proto = out.File
	file_MessageConfig_proto_goTypes = nil
	file_MessageConfig_proto_depIdxs = nil
}
