// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: NewsBulletin.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsBulletin struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewsMsgId       *int32                 `protobuf:"varint,1,opt,name=newsMsgId,proto3,oneof" json:"newsMsgId,omitempty"`
	NewsMsgType     *int32                 `protobuf:"varint,2,opt,name=newsMsgType,proto3,oneof" json:"newsMsgType,omitempty"`
	NewsMessage     *string                `protobuf:"bytes,3,opt,name=newsMessage,proto3,oneof" json:"newsMessage,omitempty"`
	OriginatingExch *string                `protobuf:"bytes,4,opt,name=originatingExch,proto3,oneof" json:"originatingExch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NewsBulletin) Reset() {
	*x = NewsBulletin{}
	mi := &file_NewsBulletin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsBulletin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsBulletin) ProtoMessage() {}

func (x *NewsBulletin) ProtoReflect() protoreflect.Message {
	mi := &file_NewsBulletin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsBulletin.ProtoReflect.Descriptor instead.
func (*NewsBulletin) Descriptor() ([]byte, []int) {
	return file_NewsBulletin_proto_rawDescGZIP(), []int{0}
}

func (x *NewsBulletin) GetNewsMsgId() int32 {
	if x != nil && x.NewsMsgId != nil {
		return *x.NewsMsgId
	}
	return 0
}

func (x *NewsBulletin) GetNewsMsgType() int32 {
	if x != nil && x.NewsMsgType != nil {
		return *x.NewsMsgType
	}
	return 0
}

func (x *NewsBulletin) GetNewsMessage() string {
	if x != nil && x.NewsMessage != nil {
		return *x.NewsMessage
	}
	return ""
}

func (x *NewsBulletin) GetOriginatingExch() string {
	if x != nil && x.OriginatingExch != nil {
		return *x.OriginatingExch
	}
	return ""
}

var File_NewsBulletin_proto protoreflect.FileDescriptor

const file_NewsBulletin_proto_rawDesc = "" +
	"\n" +
	"\x12NewsBulletin.proto\x12\bprotobuf\"\xf0\x01\n" +
	"\fNewsBulletin\x12!\n" +
	"\tnewsMsgId\x18\x01 \x01(\x05H\x00R\tnewsMsgId\x88\x01\x01\x12%\n" +
	"\vnewsMsgType\x18\x02 \x01(\x05H\x01R\vnewsMsgType\x88\x01\x01\x12%\n" +
	"\vnewsMessage\x18\x03 \x01(\tH\x02R\vnewsMessage\x88\x01\x01\x12-\n" +
	"\x0foriginatingExch\x18\x04 \x01(\tH\x03R\x0foriginatingExch\x88\x01\x01B\f\n" +
	"\n" +
	"_newsMsgIdB\x0e\n" +
	"\f_newsMsgTypeB\x0e\n" +
	"\f_newsMessageB\x12\n" +
	"\x10_originatingExchB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_NewsBulletin_proto_rawDescOnce sync.Once
	file_NewsBulletin_proto_rawDescData []byte
)

func file_NewsBulletin_proto_rawDescGZIP() []byte {
	file_NewsBulletin_proto_rawDescOnce.Do(func() {
		file_NewsBulletin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_NewsBulletin_proto_rawDesc), len(file_NewsBulletin_proto_rawDesc)))
	})
	return file_NewsBulletin_proto_rawDescData
}

var file_NewsBulletin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_NewsBulletin_proto_goTypes = []any{
	(*NewsBulletin)(nil), // 0: protobuf.NewsBulletin
}
var file_NewsBulletin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NewsBulletin_proto_init() }
func file_NewsBulletin_proto_init() {
	if File_NewsBulletin_proto != nil {
		return
	}
	file_NewsBulletin_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_NewsBulletin_proto_rawDesc), len(file_NewsBulletin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NewsBulletin_proto_goTypes,
		DependencyIndexes: file_NewsBulletin_proto_depIdxs,
		MessageInfos:      file_NewsBulletin_proto_msgTypes,
	}.Build()
	File_NewsBulletin_proto = out.File
	file_NewsBulletin_proto_goTypes = nil
	file_NewsBulletin_proto_depIdxs = nil
}
