// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: NewsProvider.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderCode  *string                `protobuf:"bytes,1,opt,name=providerCode,proto3,oneof" json:"providerCode,omitempty"`
	ProviderName  *string                `protobuf:"bytes,2,opt,name=providerName,proto3,oneof" json:"providerName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsProvider) Reset() {
	*x = NewsProvider{}
	mi := &file_NewsProvider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsProvider) ProtoMessage() {}

func (x *NewsProvider) ProtoReflect() protoreflect.Message {
	mi := &file_NewsProvider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsProvider.ProtoReflect.Descriptor instead.
func (*NewsProvider) Descriptor() ([]byte, []int) {
	return file_NewsProvider_proto_rawDescGZIP(), []int{0}
}

func (x *NewsProvider) GetProviderCode() string {
	if x != nil && x.ProviderCode != nil {
		return *x.ProviderCode
	}
	return ""
}

func (x *NewsProvider) GetProviderName() string {
	if x != nil && x.ProviderName != nil {
		return *x.ProviderName
	}
	return ""
}

var File_NewsProvider_proto protoreflect.FileDescriptor

var file_NewsProvider_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x4e, 0x65, 0x77, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x82,
	0x01, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_NewsProvider_proto_rawDescOnce sync.Once
	file_NewsProvider_proto_rawDescData []byte
)

func file_NewsProvider_proto_rawDescGZIP() []byte {
	file_NewsProvider_proto_rawDescOnce.Do(func() {
		file_NewsProvider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_NewsProvider_proto_rawDesc), len(file_NewsProvider_proto_rawDesc)))
	})
	return file_NewsProvider_proto_rawDescData
}

var file_NewsProvider_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_NewsProvider_proto_goTypes = []any{
	(*NewsProvider)(nil), // 0: protobuf.NewsProvider
}
var file_NewsProvider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NewsProvider_proto_init() }
func file_NewsProvider_proto_init() {
	if File_NewsProvider_proto != nil {
		return
	}
	file_NewsProvider_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_NewsProvider_proto_rawDesc), len(file_NewsProvider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NewsProvider_proto_goTypes,
		DependencyIndexes: file_NewsProvider_proto_depIdxs,
		MessageInfos:      file_NewsProvider_proto_msgTypes,
	}.Build()
	File_NewsProvider_proto = out.File
	file_NewsProvider_proto_goTypes = nil
	file_NewsProvider_proto_depIdxs = nil
}
