// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: OrderAllocation.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderAllocation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Account         *string                `protobuf:"bytes,1,opt,name=account,proto3,oneof" json:"account,omitempty"`
	Position        *string                `protobuf:"bytes,2,opt,name=position,proto3,oneof" json:"position,omitempty"`
	PositionDesired *string                `protobuf:"bytes,3,opt,name=positionDesired,proto3,oneof" json:"positionDesired,omitempty"`
	PositionAfter   *string                `protobuf:"bytes,4,opt,name=positionAfter,proto3,oneof" json:"positionAfter,omitempty"`
	DesiredAllocQty *string                `protobuf:"bytes,5,opt,name=desiredAllocQty,proto3,oneof" json:"desiredAllocQty,omitempty"`
	AllowedAllocQty *string                `protobuf:"bytes,6,opt,name=allowedAllocQty,proto3,oneof" json:"allowedAllocQty,omitempty"`
	IsMonetary      *bool                  `protobuf:"varint,7,opt,name=isMonetary,proto3,oneof" json:"isMonetary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderAllocation) Reset() {
	*x = OrderAllocation{}
	mi := &file_OrderAllocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAllocation) ProtoMessage() {}

func (x *OrderAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_OrderAllocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAllocation.ProtoReflect.Descriptor instead.
func (*OrderAllocation) Descriptor() ([]byte, []int) {
	return file_OrderAllocation_proto_rawDescGZIP(), []int{0}
}

func (x *OrderAllocation) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *OrderAllocation) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *OrderAllocation) GetPositionDesired() string {
	if x != nil && x.PositionDesired != nil {
		return *x.PositionDesired
	}
	return ""
}

func (x *OrderAllocation) GetPositionAfter() string {
	if x != nil && x.PositionAfter != nil {
		return *x.PositionAfter
	}
	return ""
}

func (x *OrderAllocation) GetDesiredAllocQty() string {
	if x != nil && x.DesiredAllocQty != nil {
		return *x.DesiredAllocQty
	}
	return ""
}

func (x *OrderAllocation) GetAllowedAllocQty() string {
	if x != nil && x.AllowedAllocQty != nil {
		return *x.AllowedAllocQty
	}
	return ""
}

func (x *OrderAllocation) GetIsMonetary() bool {
	if x != nil && x.IsMonetary != nil {
		return *x.IsMonetary
	}
	return false
}

var File_OrderAllocation_proto protoreflect.FileDescriptor

const file_OrderAllocation_proto_rawDesc = "" +
	"\n" +
	"\x15OrderAllocation.proto\x12\bprotobuf\"\xa4\x03\n" +
	"\x0fOrderAllocation\x12\x1d\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\x02 \x01(\tH\x01R\bposition\x88\x01\x01\x12-\n" +
	"\x0fpositionDesired\x18\x03 \x01(\tH\x02R\x0fpositionDesired\x88\x01\x01\x12)\n" +
	"\rpositionAfter\x18\x04 \x01(\tH\x03R\rpositionAfter\x88\x01\x01\x12-\n" +
	"\x0fdesiredAllocQty\x18\x05 \x01(\tH\x04R\x0fdesiredAllocQty\x88\x01\x01\x12-\n" +
	"\x0fallowedAllocQty\x18\x06 \x01(\tH\x05R\x0fallowedAllocQty\x88\x01\x01\x12#\n" +
	"\n" +
	"isMonetary\x18\a \x01(\bH\x06R\n" +
	"isMonetary\x88\x01\x01B\n" +
	"\n" +
	"\b_accountB\v\n" +
	"\t_positionB\x12\n" +
	"\x10_positionDesiredB\x10\n" +
	"\x0e_positionAfterB\x12\n" +
	"\x10_desiredAllocQtyB\x12\n" +
	"\x10_allowedAllocQtyB\r\n" +
	"\v_isMonetaryB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_OrderAllocation_proto_rawDescOnce sync.Once
	file_OrderAllocation_proto_rawDescData []byte
)

func file_OrderAllocation_proto_rawDescGZIP() []byte {
	file_OrderAllocation_proto_rawDescOnce.Do(func() {
		file_OrderAllocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OrderAllocation_proto_rawDesc), len(file_OrderAllocation_proto_rawDesc)))
	})
	return file_OrderAllocation_proto_rawDescData
}

var file_OrderAllocation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OrderAllocation_proto_goTypes = []any{
	(*OrderAllocation)(nil), // 0: protobuf.OrderAllocation
}
var file_OrderAllocation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_OrderAllocation_proto_init() }
func file_OrderAllocation_proto_init() {
	if File_OrderAllocation_proto != nil {
		return
	}
	file_OrderAllocation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OrderAllocation_proto_rawDesc), len(file_OrderAllocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OrderAllocation_proto_goTypes,
		DependencyIndexes: file_OrderAllocation_proto_depIdxs,
		MessageInfos:      file_OrderAllocation_proto_msgTypes,
	}.Build()
	File_OrderAllocation_proto = out.File
	file_OrderAllocation_proto_goTypes = nil
	file_OrderAllocation_proto_depIdxs = nil
}
