// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: OrderBound.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderBound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermId        *int64                 `protobuf:"varint,1,opt,name=permId,proto3,oneof" json:"permId,omitempty"`
	ClientId      *int32                 `protobuf:"varint,2,opt,name=clientId,proto3,oneof" json:"clientId,omitempty"`
	OrderId       *int32                 `protobuf:"varint,3,opt,name=orderId,proto3,oneof" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBound) Reset() {
	*x = OrderBound{}
	mi := &file_OrderBound_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBound) ProtoMessage() {}

func (x *OrderBound) ProtoReflect() protoreflect.Message {
	mi := &file_OrderBound_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBound.ProtoReflect.Descriptor instead.
func (*OrderBound) Descriptor() ([]byte, []int) {
	return file_OrderBound_proto_rawDescGZIP(), []int{0}
}

func (x *OrderBound) GetPermId() int64 {
	if x != nil && x.PermId != nil {
		return *x.PermId
	}
	return 0
}

func (x *OrderBound) GetClientId() int32 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *OrderBound) GetOrderId() int32 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

var File_OrderBound_proto protoreflect.FileDescriptor

var file_OrderBound_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x8d, 0x01, 0x0a,
	0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x70,
	0x65, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x70,
	0x65, 0x72, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x70, 0x65, 0x72,
	0x6d, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_OrderBound_proto_rawDescOnce sync.Once
	file_OrderBound_proto_rawDescData []byte
)

func file_OrderBound_proto_rawDescGZIP() []byte {
	file_OrderBound_proto_rawDescOnce.Do(func() {
		file_OrderBound_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OrderBound_proto_rawDesc), len(file_OrderBound_proto_rawDesc)))
	})
	return file_OrderBound_proto_rawDescData
}

var file_OrderBound_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OrderBound_proto_goTypes = []any{
	(*OrderBound)(nil), // 0: protobuf.OrderBound
}
var file_OrderBound_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_OrderBound_proto_init() }
func file_OrderBound_proto_init() {
	if File_OrderBound_proto != nil {
		return
	}
	file_OrderBound_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OrderBound_proto_rawDesc), len(file_OrderBound_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OrderBound_proto_goTypes,
		DependencyIndexes: file_OrderBound_proto_depIdxs,
		MessageInfos:      file_OrderBound_proto_msgTypes,
	}.Build()
	File_OrderBound_proto = out.File
	file_OrderBound_proto_goTypes = nil
	file_OrderBound_proto_depIdxs = nil
}
