// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: OrderStatus.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *int32                 `protobuf:"varint,1,opt,name=orderId,proto3,oneof" json:"orderId,omitempty"`
	Status        *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Filled        *string                `protobuf:"bytes,3,opt,name=filled,proto3,oneof" json:"filled,omitempty"`
	Remaining     *string                `protobuf:"bytes,4,opt,name=remaining,proto3,oneof" json:"remaining,omitempty"`
	AvgFillPrice  *float64               `protobuf:"fixed64,5,opt,name=avgFillPrice,proto3,oneof" json:"avgFillPrice,omitempty"`
	PermId        *int64                 `protobuf:"varint,6,opt,name=permId,proto3,oneof" json:"permId,omitempty"`
	ParentId      *int32                 `protobuf:"varint,7,opt,name=parentId,proto3,oneof" json:"parentId,omitempty"`
	LastFillPrice *float64               `protobuf:"fixed64,8,opt,name=lastFillPrice,proto3,oneof" json:"lastFillPrice,omitempty"`
	ClientId      *int32                 `protobuf:"varint,9,opt,name=clientId,proto3,oneof" json:"clientId,omitempty"`
	WhyHeld       *string                `protobuf:"bytes,10,opt,name=whyHeld,proto3,oneof" json:"whyHeld,omitempty"`
	MktCapPrice   *float64               `protobuf:"fixed64,11,opt,name=mktCapPrice,proto3,oneof" json:"mktCapPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_OrderStatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_OrderStatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_OrderStatus_proto_rawDescGZIP(), []int{0}
}

func (x *OrderStatus) GetOrderId() int32 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *OrderStatus) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *OrderStatus) GetFilled() string {
	if x != nil && x.Filled != nil {
		return *x.Filled
	}
	return ""
}

func (x *OrderStatus) GetRemaining() string {
	if x != nil && x.Remaining != nil {
		return *x.Remaining
	}
	return ""
}

func (x *OrderStatus) GetAvgFillPrice() float64 {
	if x != nil && x.AvgFillPrice != nil {
		return *x.AvgFillPrice
	}
	return 0
}

func (x *OrderStatus) GetPermId() int64 {
	if x != nil && x.PermId != nil {
		return *x.PermId
	}
	return 0
}

func (x *OrderStatus) GetParentId() int32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *OrderStatus) GetLastFillPrice() float64 {
	if x != nil && x.LastFillPrice != nil {
		return *x.LastFillPrice
	}
	return 0
}

func (x *OrderStatus) GetClientId() int32 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (x *OrderStatus) GetWhyHeld() string {
	if x != nil && x.WhyHeld != nil {
		return *x.WhyHeld
	}
	return ""
}

func (x *OrderStatus) GetMktCapPrice() float64 {
	if x != nil && x.MktCapPrice != nil {
		return *x.MktCapPrice
	}
	return 0
}

var File_OrderStatus_proto protoreflect.FileDescriptor

const file_OrderStatus_proto_rawDesc = "" +
	"\n" +
	"\x11OrderStatus.proto\x12\bprotobuf\"\x96\x04\n" +
	"\vOrderStatus\x12\x1d\n" +
	"\aorderId\x18\x01 \x01(\x05H\x00R\aorderId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06filled\x18\x03 \x01(\tH\x02R\x06filled\x88\x01\x01\x12!\n" +
	"\tremaining\x18\x04 \x01(\tH\x03R\tremaining\x88\x01\x01\x12'\n" +
	"\favgFillPrice\x18\x05 \x01(\x01H\x04R\favgFillPrice\x88\x01\x01\x12\x1b\n" +
	"\x06permId\x18\x06 \x01(\x03H\x05R\x06permId\x88\x01\x01\x12\x1f\n" +
	"\bparentId\x18\a \x01(\x05H\x06R\bparentId\x88\x01\x01\x12)\n" +
	"\rlastFillPrice\x18\b \x01(\x01H\aR\rlastFillPrice\x88\x01\x01\x12\x1f\n" +
	"\bclientId\x18\t \x01(\x05H\bR\bclientId\x88\x01\x01\x12\x1d\n" +
	"\awhyHeld\x18\n" +
	" \x01(\tH\tR\awhyHeld\x88\x01\x01\x12%\n" +
	"\vmktCapPrice\x18\v \x01(\x01H\n" +
	"R\vmktCapPrice\x88\x01\x01B\n" +
	"\n" +
	"\b_orderIdB\t\n" +
	"\a_statusB\t\n" +
	"\a_filledB\f\n" +
	"\n" +
	"_remainingB\x0f\n" +
	"\r_avgFillPriceB\t\n" +
	"\a_permIdB\v\n" +
	"\t_parentIdB\x10\n" +
	"\x0e_lastFillPriceB\v\n" +
	"\t_clientIdB\n" +
	"\n" +
	"\b_whyHeldB\x0e\n" +
	"\f_mktCapPriceB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_OrderStatus_proto_rawDescOnce sync.Once
	file_OrderStatus_proto_rawDescData []byte
)

func file_OrderStatus_proto_rawDescGZIP() []byte {
	file_OrderStatus_proto_rawDescOnce.Do(func() {
		file_OrderStatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OrderStatus_proto_rawDesc), len(file_OrderStatus_proto_rawDesc)))
	})
	return file_OrderStatus_proto_rawDescData
}

var file_OrderStatus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OrderStatus_proto_goTypes = []any{
	(*OrderStatus)(nil), // 0: protobuf.OrderStatus
}
var file_OrderStatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_OrderStatus_proto_init() }
func file_OrderStatus_proto_init() {
	if File_OrderStatus_proto != nil {
		return
	}
	file_OrderStatus_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OrderStatus_proto_rawDesc), len(file_OrderStatus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OrderStatus_proto_goTypes,
		DependencyIndexes: file_OrderStatus_proto_depIdxs,
		MessageInfos:      file_OrderStatus_proto_msgTypes,
	}.Build()
	File_OrderStatus_proto = out.File
	file_OrderStatus_proto_goTypes = nil
	file_OrderStatus_proto_depIdxs = nil
}
