// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: OrderState.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderState struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Status                         *string                `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	InitMarginBefore               *float64               `protobuf:"fixed64,2,opt,name=initMarginBefore,proto3,oneof" json:"initMarginBefore,omitempty"`
	MaintMarginBefore              *float64               `protobuf:"fixed64,3,opt,name=maintMarginBefore,proto3,oneof" json:"maintMarginBefore,omitempty"`
	EquityWithLoanBefore           *float64               `protobuf:"fixed64,4,opt,name=equityWithLoanBefore,proto3,oneof" json:"equityWithLoanBefore,omitempty"`
	InitMarginChange               *float64               `protobuf:"fixed64,5,opt,name=initMarginChange,proto3,oneof" json:"initMarginChange,omitempty"`
	MaintMarginChange              *float64               `protobuf:"fixed64,6,opt,name=maintMarginChange,proto3,oneof" json:"maintMarginChange,omitempty"`
	EquityWithLoanChange           *float64               `protobuf:"fixed64,7,opt,name=equityWithLoanChange,proto3,oneof" json:"equityWithLoanChange,omitempty"`
	InitMarginAfter                *float64               `protobuf:"fixed64,8,opt,name=initMarginAfter,proto3,oneof" json:"initMarginAfter,omitempty"`
	MaintMarginAfter               *float64               `protobuf:"fixed64,9,opt,name=maintMarginAfter,proto3,oneof" json:"maintMarginAfter,omitempty"`
	EquityWithLoanAfter            *float64               `protobuf:"fixed64,10,opt,name=equityWithLoanAfter,proto3,oneof" json:"equityWithLoanAfter,omitempty"`
	CommissionAndFees              *float64               `protobuf:"fixed64,11,opt,name=commissionAndFees,proto3,oneof" json:"commissionAndFees,omitempty"`
	MinCommissionAndFees           *float64               `protobuf:"fixed64,12,opt,name=minCommissionAndFees,proto3,oneof" json:"minCommissionAndFees,omitempty"`
	MaxCommissionAndFees           *float64               `protobuf:"fixed64,13,opt,name=maxCommissionAndFees,proto3,oneof" json:"maxCommissionAndFees,omitempty"`
	CommissionAndFeesCurrency      *string                `protobuf:"bytes,14,opt,name=commissionAndFeesCurrency,proto3,oneof" json:"commissionAndFeesCurrency,omitempty"`
	MarginCurrency                 *string                `protobuf:"bytes,15,opt,name=marginCurrency,proto3,oneof" json:"marginCurrency,omitempty"`
	InitMarginBeforeOutsideRTH     *float64               `protobuf:"fixed64,16,opt,name=initMarginBeforeOutsideRTH,proto3,oneof" json:"initMarginBeforeOutsideRTH,omitempty"`
	MaintMarginBeforeOutsideRTH    *float64               `protobuf:"fixed64,17,opt,name=maintMarginBeforeOutsideRTH,proto3,oneof" json:"maintMarginBeforeOutsideRTH,omitempty"`
	EquityWithLoanBeforeOutsideRTH *float64               `protobuf:"fixed64,18,opt,name=equityWithLoanBeforeOutsideRTH,proto3,oneof" json:"equityWithLoanBeforeOutsideRTH,omitempty"`
	InitMarginChangeOutsideRTH     *float64               `protobuf:"fixed64,19,opt,name=initMarginChangeOutsideRTH,proto3,oneof" json:"initMarginChangeOutsideRTH,omitempty"`
	MaintMarginChangeOutsideRTH    *float64               `protobuf:"fixed64,20,opt,name=maintMarginChangeOutsideRTH,proto3,oneof" json:"maintMarginChangeOutsideRTH,omitempty"`
	EquityWithLoanChangeOutsideRTH *float64               `protobuf:"fixed64,21,opt,name=equityWithLoanChangeOutsideRTH,proto3,oneof" json:"equityWithLoanChangeOutsideRTH,omitempty"`
	InitMarginAfterOutsideRTH      *float64               `protobuf:"fixed64,22,opt,name=initMarginAfterOutsideRTH,proto3,oneof" json:"initMarginAfterOutsideRTH,omitempty"`
	MaintMarginAfterOutsideRTH     *float64               `protobuf:"fixed64,23,opt,name=maintMarginAfterOutsideRTH,proto3,oneof" json:"maintMarginAfterOutsideRTH,omitempty"`
	EquityWithLoanAfterOutsideRTH  *float64               `protobuf:"fixed64,24,opt,name=equityWithLoanAfterOutsideRTH,proto3,oneof" json:"equityWithLoanAfterOutsideRTH,omitempty"`
	SuggestedSize                  *string                `protobuf:"bytes,25,opt,name=suggestedSize,proto3,oneof" json:"suggestedSize,omitempty"`
	RejectReason                   *string                `protobuf:"bytes,26,opt,name=rejectReason,proto3,oneof" json:"rejectReason,omitempty"`
	OrderAllocations               []*OrderAllocation     `protobuf:"bytes,27,rep,name=orderAllocations,proto3" json:"orderAllocations,omitempty"`
	WarningText                    *string                `protobuf:"bytes,28,opt,name=warningText,proto3,oneof" json:"warningText,omitempty"`
	CompletedTime                  *string                `protobuf:"bytes,29,opt,name=completedTime,proto3,oneof" json:"completedTime,omitempty"`
	CompletedStatus                *string                `protobuf:"bytes,30,opt,name=completedStatus,proto3,oneof" json:"completedStatus,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *OrderState) Reset() {
	*x = OrderState{}
	mi := &file_OrderState_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderState) ProtoMessage() {}

func (x *OrderState) ProtoReflect() protoreflect.Message {
	mi := &file_OrderState_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderState.ProtoReflect.Descriptor instead.
func (*OrderState) Descriptor() ([]byte, []int) {
	return file_OrderState_proto_rawDescGZIP(), []int{0}
}

func (x *OrderState) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *OrderState) GetInitMarginBefore() float64 {
	if x != nil && x.InitMarginBefore != nil {
		return *x.InitMarginBefore
	}
	return 0
}

func (x *OrderState) GetMaintMarginBefore() float64 {
	if x != nil && x.MaintMarginBefore != nil {
		return *x.MaintMarginBefore
	}
	return 0
}

func (x *OrderState) GetEquityWithLoanBefore() float64 {
	if x != nil && x.EquityWithLoanBefore != nil {
		return *x.EquityWithLoanBefore
	}
	return 0
}

func (x *OrderState) GetInitMarginChange() float64 {
	if x != nil && x.InitMarginChange != nil {
		return *x.InitMarginChange
	}
	return 0
}

func (x *OrderState) GetMaintMarginChange() float64 {
	if x != nil && x.MaintMarginChange != nil {
		return *x.MaintMarginChange
	}
	return 0
}

func (x *OrderState) GetEquityWithLoanChange() float64 {
	if x != nil && x.EquityWithLoanChange != nil {
		return *x.EquityWithLoanChange
	}
	return 0
}

func (x *OrderState) GetInitMarginAfter() float64 {
	if x != nil && x.InitMarginAfter != nil {
		return *x.InitMarginAfter
	}
	return 0
}

func (x *OrderState) GetMaintMarginAfter() float64 {
	if x != nil && x.MaintMarginAfter != nil {
		return *x.MaintMarginAfter
	}
	return 0
}

func (x *OrderState) GetEquityWithLoanAfter() float64 {
	if x != nil && x.EquityWithLoanAfter != nil {
		return *x.EquityWithLoanAfter
	}
	return 0
}

func (x *OrderState) GetCommissionAndFees() float64 {
	if x != nil && x.CommissionAndFees != nil {
		return *x.CommissionAndFees
	}
	return 0
}

func (x *OrderState) GetMinCommissionAndFees() float64 {
	if x != nil && x.MinCommissionAndFees != nil {
		return *x.MinCommissionAndFees
	}
	return 0
}

func (x *OrderState) GetMaxCommissionAndFees() float64 {
	if x != nil && x.MaxCommissionAndFees != nil {
		return *x.MaxCommissionAndFees
	}
	return 0
}

func (x *OrderState) GetCommissionAndFeesCurrency() string {
	if x != nil && x.CommissionAndFeesCurrency != nil {
		return *x.CommissionAndFeesCurrency
	}
	return ""
}

func (x *OrderState) GetMarginCurrency() string {
	if x != nil && x.MarginCurrency != nil {
		return *x.MarginCurrency
	}
	return ""
}

func (x *OrderState) GetInitMarginBeforeOutsideRTH() float64 {
	if x != nil && x.InitMarginBeforeOutsideRTH != nil {
		return *x.InitMarginBeforeOutsideRTH
	}
	return 0
}

func (x *OrderState) GetMaintMarginBeforeOutsideRTH() float64 {
	if x != nil && x.MaintMarginBeforeOutsideRTH != nil {
		return *x.MaintMarginBeforeOutsideRTH
	}
	return 0
}

func (x *OrderState) GetEquityWithLoanBeforeOutsideRTH() float64 {
	if x != nil && x.EquityWithLoanBeforeOutsideRTH != nil {
		return *x.EquityWithLoanBeforeOutsideRTH
	}
	return 0
}

func (x *OrderState) GetInitMarginChangeOutsideRTH() float64 {
	if x != nil && x.InitMarginChangeOutsideRTH != nil {
		return *x.InitMarginChangeOutsideRTH
	}
	return 0
}

func (x *OrderState) GetMaintMarginChangeOutsideRTH() float64 {
	if x != nil && x.MaintMarginChangeOutsideRTH != nil {
		return *x.MaintMarginChangeOutsideRTH
	}
	return 0
}

func (x *OrderState) GetEquityWithLoanChangeOutsideRTH() float64 {
	if x != nil && x.EquityWithLoanChangeOutsideRTH != nil {
		return *x.EquityWithLoanChangeOutsideRTH
	}
	return 0
}

func (x *OrderState) GetInitMarginAfterOutsideRTH() float64 {
	if x != nil && x.InitMarginAfterOutsideRTH != nil {
		return *x.InitMarginAfterOutsideRTH
	}
	return 0
}

func (x *OrderState) GetMaintMarginAfterOutsideRTH() float64 {
	if x != nil && x.MaintMarginAfterOutsideRTH != nil {
		return *x.MaintMarginAfterOutsideRTH
	}
	return 0
}

func (x *OrderState) GetEquityWithLoanAfterOutsideRTH() float64 {
	if x != nil && x.EquityWithLoanAfterOutsideRTH != nil {
		return *x.EquityWithLoanAfterOutsideRTH
	}
	return 0
}

func (x *OrderState) GetSuggestedSize() string {
	if x != nil && x.SuggestedSize != nil {
		return *x.SuggestedSize
	}
	return ""
}

func (x *OrderState) GetRejectReason() string {
	if x != nil && x.RejectReason != nil {
		return *x.RejectReason
	}
	return ""
}

func (x *OrderState) GetOrderAllocations() []*OrderAllocation {
	if x != nil {
		return x.OrderAllocations
	}
	return nil
}

func (x *OrderState) GetWarningText() string {
	if x != nil && x.WarningText != nil {
		return *x.WarningText
	}
	return ""
}

func (x *OrderState) GetCompletedTime() string {
	if x != nil && x.CompletedTime != nil {
		return *x.CompletedTime
	}
	return ""
}

func (x *OrderState) GetCompletedStatus() string {
	if x != nil && x.CompletedStatus != nil {
		return *x.CompletedStatus
	}
	return ""
}

var File_OrderState_proto protoreflect.FileDescriptor

const file_OrderState_proto_rawDesc = "" +
	"\n" +
	"\x10OrderState.proto\x12\bprotobuf\x1a\x15OrderAllocation.proto\"\xf9\x12\n" +
	"\n" +
	"OrderState\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\tH\x00R\x06status\x88\x01\x01\x12/\n" +
	"\x10initMarginBefore\x18\x02 \x01(\x01H\x01R\x10initMarginBefore\x88\x01\x01\x121\n" +
	"\x11maintMarginBefore\x18\x03 \x01(\x01H\x02R\x11maintMarginBefore\x88\x01\x01\x127\n" +
	"\x14equityWithLoanBefore\x18\x04 \x01(\x01H\x03R\x14equityWithLoanBefore\x88\x01\x01\x12/\n" +
	"\x10initMarginChange\x18\x05 \x01(\x01H\x04R\x10initMarginChange\x88\x01\x01\x121\n" +
	"\x11maintMarginChange\x18\x06 \x01(\x01H\x05R\x11maintMarginChange\x88\x01\x01\x127\n" +
	"\x14equityWithLoanChange\x18\a \x01(\x01H\x06R\x14equityWithLoanChange\x88\x01\x01\x12-\n" +
	"\x0finitMarginAfter\x18\b \x01(\x01H\aR\x0finitMarginAfter\x88\x01\x01\x12/\n" +
	"\x10maintMarginAfter\x18\t \x01(\x01H\bR\x10maintMarginAfter\x88\x01\x01\x125\n" +
	"\x13equityWithLoanAfter\x18\n" +
	" \x01(\x01H\tR\x13equityWithLoanAfter\x88\x01\x01\x121\n" +
	"\x11commissionAndFees\x18\v \x01(\x01H\n" +
	"R\x11commissionAndFees\x88\x01\x01\x127\n" +
	"\x14minCommissionAndFees\x18\f \x01(\x01H\vR\x14minCommissionAndFees\x88\x01\x01\x127\n" +
	"\x14maxCommissionAndFees\x18\r \x01(\x01H\fR\x14maxCommissionAndFees\x88\x01\x01\x12A\n" +
	"\x19commissionAndFeesCurrency\x18\x0e \x01(\tH\rR\x19commissionAndFeesCurrency\x88\x01\x01\x12+\n" +
	"\x0emarginCurrency\x18\x0f \x01(\tH\x0eR\x0emarginCurrency\x88\x01\x01\x12C\n" +
	"\x1ainitMarginBeforeOutsideRTH\x18\x10 \x01(\x01H\x0fR\x1ainitMarginBeforeOutsideRTH\x88\x01\x01\x12E\n" +
	"\x1bmaintMarginBeforeOutsideRTH\x18\x11 \x01(\x01H\x10R\x1bmaintMarginBeforeOutsideRTH\x88\x01\x01\x12K\n" +
	"\x1eequityWithLoanBeforeOutsideRTH\x18\x12 \x01(\x01H\x11R\x1eequityWithLoanBeforeOutsideRTH\x88\x01\x01\x12C\n" +
	"\x1ainitMarginChangeOutsideRTH\x18\x13 \x01(\x01H\x12R\x1ainitMarginChangeOutsideRTH\x88\x01\x01\x12E\n" +
	"\x1bmaintMarginChangeOutsideRTH\x18\x14 \x01(\x01H\x13R\x1bmaintMarginChangeOutsideRTH\x88\x01\x01\x12K\n" +
	"\x1eequityWithLoanChangeOutsideRTH\x18\x15 \x01(\x01H\x14R\x1eequityWithLoanChangeOutsideRTH\x88\x01\x01\x12A\n" +
	"\x19initMarginAfterOutsideRTH\x18\x16 \x01(\x01H\x15R\x19initMarginAfterOutsideRTH\x88\x01\x01\x12C\n" +
	"\x1amaintMarginAfterOutsideRTH\x18\x17 \x01(\x01H\x16R\x1amaintMarginAfterOutsideRTH\x88\x01\x01\x12I\n" +
	"\x1dequityWithLoanAfterOutsideRTH\x18\x18 \x01(\x01H\x17R\x1dequityWithLoanAfterOutsideRTH\x88\x01\x01\x12)\n" +
	"\rsuggestedSize\x18\x19 \x01(\tH\x18R\rsuggestedSize\x88\x01\x01\x12'\n" +
	"\frejectReason\x18\x1a \x01(\tH\x19R\frejectReason\x88\x01\x01\x12E\n" +
	"\x10orderAllocations\x18\x1b \x03(\v2\x19.protobuf.OrderAllocationR\x10orderAllocations\x12%\n" +
	"\vwarningText\x18\x1c \x01(\tH\x1aR\vwarningText\x88\x01\x01\x12)\n" +
	"\rcompletedTime\x18\x1d \x01(\tH\x1bR\rcompletedTime\x88\x01\x01\x12-\n" +
	"\x0fcompletedStatus\x18\x1e \x01(\tH\x1cR\x0fcompletedStatus\x88\x01\x01B\t\n" +
	"\a_statusB\x13\n" +
	"\x11_initMarginBeforeB\x14\n" +
	"\x12_maintMarginBeforeB\x17\n" +
	"\x15_equityWithLoanBeforeB\x13\n" +
	"\x11_initMarginChangeB\x14\n" +
	"\x12_maintMarginChangeB\x17\n" +
	"\x15_equityWithLoanChangeB\x12\n" +
	"\x10_initMarginAfterB\x13\n" +
	"\x11_maintMarginAfterB\x16\n" +
	"\x14_equityWithLoanAfterB\x14\n" +
	"\x12_commissionAndFeesB\x17\n" +
	"\x15_minCommissionAndFeesB\x17\n" +
	"\x15_maxCommissionAndFeesB\x1c\n" +
	"\x1a_commissionAndFeesCurrencyB\x11\n" +
	"\x0f_marginCurrencyB\x1d\n" +
	"\x1b_initMarginBeforeOutsideRTHB\x1e\n" +
	"\x1c_maintMarginBeforeOutsideRTHB!\n" +
	"\x1f_equityWithLoanBeforeOutsideRTHB\x1d\n" +
	"\x1b_initMarginChangeOutsideRTHB\x1e\n" +
	"\x1c_maintMarginChangeOutsideRTHB!\n" +
	"\x1f_equityWithLoanChangeOutsideRTHB\x1c\n" +
	"\x1a_initMarginAfterOutsideRTHB\x1d\n" +
	"\x1b_maintMarginAfterOutsideRTHB \n" +
	"\x1e_equityWithLoanAfterOutsideRTHB\x10\n" +
	"\x0e_suggestedSizeB\x0f\n" +
	"\r_rejectReasonB\x0e\n" +
	"\f_warningTextB\x10\n" +
	"\x0e_completedTimeB\x12\n" +
	"\x10_completedStatusB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_OrderState_proto_rawDescOnce sync.Once
	file_OrderState_proto_rawDescData []byte
)

func file_OrderState_proto_rawDescGZIP() []byte {
	file_OrderState_proto_rawDescOnce.Do(func() {
		file_OrderState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OrderState_proto_rawDesc), len(file_OrderState_proto_rawDesc)))
	})
	return file_OrderState_proto_rawDescData
}

var file_OrderState_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OrderState_proto_goTypes = []any{
	(*OrderState)(nil),      // 0: protobuf.OrderState
	(*OrderAllocation)(nil), // 1: protobuf.OrderAllocation
}
var file_OrderState_proto_depIdxs = []int32{
	1, // 0: protobuf.OrderState.orderAllocations:type_name -> protobuf.OrderAllocation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_OrderState_proto_init() }
func file_OrderState_proto_init() {
	if File_OrderState_proto != nil {
		return
	}
	file_OrderAllocation_proto_init()
	file_OrderState_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OrderState_proto_rawDesc), len(file_OrderState_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OrderState_proto_goTypes,
		DependencyIndexes: file_OrderState_proto_depIdxs,
		MessageInfos:      file_OrderState_proto_msgTypes,
	}.Build()
	File_OrderState_proto = out.File
	file_OrderState_proto_goTypes = nil
	file_OrderState_proto_depIdxs = nil
}
