// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: PlaceOrderRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *int32                 `protobuf:"varint,1,opt,name=orderId,proto3,oneof" json:"orderId,omitempty"`
	Contract      *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	Order         *Order                 `protobuf:"bytes,3,opt,name=order,proto3,oneof" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_PlaceOrderRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PlaceOrderRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_PlaceOrderRequest_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetOrderId() int32 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *PlaceOrderRequest) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *PlaceOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_PlaceOrderRequest_proto protoreflect.FileDescriptor

const file_PlaceOrderRequest_proto_rawDesc = "" +
	"\n" +
	"\x17PlaceOrderRequest.proto\x12\bprotobuf\x1a\x0eContract.proto\x1a\vOrder.proto\"\xb6\x01\n" +
	"\x11PlaceOrderRequest\x12\x1d\n" +
	"\aorderId\x18\x01 \x01(\x05H\x00R\aorderId\x88\x01\x01\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x12.protobuf.ContractH\x01R\bcontract\x88\x01\x01\x12*\n" +
	"\x05order\x18\x03 \x01(\v2\x0f.protobuf.OrderH\x02R\x05order\x88\x01\x01B\n" +
	"\n" +
	"\b_orderIdB\v\n" +
	"\t_contractB\b\n" +
	"\x06_orderB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PlaceOrderRequest_proto_rawDescOnce sync.Once
	file_PlaceOrderRequest_proto_rawDescData []byte
)

func file_PlaceOrderRequest_proto_rawDescGZIP() []byte {
	file_PlaceOrderRequest_proto_rawDescOnce.Do(func() {
		file_PlaceOrderRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PlaceOrderRequest_proto_rawDesc), len(file_PlaceOrderRequest_proto_rawDesc)))
	})
	return file_PlaceOrderRequest_proto_rawDescData
}

var file_PlaceOrderRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlaceOrderRequest_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil), // 0: protobuf.PlaceOrderRequest
	(*Contract)(nil),          // 1: protobuf.Contract
	(*Order)(nil),             // 2: protobuf.Order
}
var file_PlaceOrderRequest_proto_depIdxs = []int32{
	1, // 0: protobuf.PlaceOrderRequest.contract:type_name -> protobuf.Contract
	2, // 1: protobuf.PlaceOrderRequest.order:type_name -> protobuf.Order
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PlaceOrderRequest_proto_init() }
func file_PlaceOrderRequest_proto_init() {
	if File_PlaceOrderRequest_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_Order_proto_init()
	file_PlaceOrderRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PlaceOrderRequest_proto_rawDesc), len(file_PlaceOrderRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlaceOrderRequest_proto_goTypes,
		DependencyIndexes: file_PlaceOrderRequest_proto_depIdxs,
		MessageInfos:      file_PlaceOrderRequest_proto_msgTypes,
	}.Build()
	File_PlaceOrderRequest_proto = out.File
	file_PlaceOrderRequest_proto_goTypes = nil
	file_PlaceOrderRequest_proto_depIdxs = nil
}
