// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: PnL.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PnL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	DailyPnL      *float64               `protobuf:"fixed64,2,opt,name=dailyPnL,proto3,oneof" json:"dailyPnL,omitempty"`
	UnrealizedPnL *float64               `protobuf:"fixed64,3,opt,name=unrealizedPnL,proto3,oneof" json:"unrealizedPnL,omitempty"`
	RealizedPnL   *float64               `protobuf:"fixed64,4,opt,name=realizedPnL,proto3,oneof" json:"realizedPnL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PnL) Reset() {
	*x = PnL{}
	mi := &file_PnL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PnL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PnL) ProtoMessage() {}

func (x *PnL) ProtoReflect() protoreflect.Message {
	mi := &file_PnL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PnL.ProtoReflect.Descriptor instead.
func (*PnL) Descriptor() ([]byte, []int) {
	return file_PnL_proto_rawDescGZIP(), []int{0}
}

func (x *PnL) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *PnL) GetDailyPnL() float64 {
	if x != nil && x.DailyPnL != nil {
		return *x.DailyPnL
	}
	return 0
}

func (x *PnL) GetUnrealizedPnL() float64 {
	if x != nil && x.UnrealizedPnL != nil {
		return *x.UnrealizedPnL
	}
	return 0
}

func (x *PnL) GetRealizedPnL() float64 {
	if x != nil && x.RealizedPnL != nil {
		return *x.RealizedPnL
	}
	return 0
}

var File_PnL_proto protoreflect.FileDescriptor

const file_PnL_proto_rawDesc = "" +
	"\n" +
	"\tPnL.proto\x12\bprotobuf\"\xcc\x01\n" +
	"\x03PnL\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12\x1f\n" +
	"\bdailyPnL\x18\x02 \x01(\x01H\x01R\bdailyPnL\x88\x01\x01\x12)\n" +
	"\runrealizedPnL\x18\x03 \x01(\x01H\x02R\runrealizedPnL\x88\x01\x01\x12%\n" +
	"\vrealizedPnL\x18\x04 \x01(\x01H\x03R\vrealizedPnL\x88\x01\x01B\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_dailyPnLB\x10\n" +
	"\x0e_unrealizedPnLB\x0e\n" +
	"\f_realizedPnLB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PnL_proto_rawDescOnce sync.Once
	file_PnL_proto_rawDescData []byte
)

func file_PnL_proto_rawDescGZIP() []byte {
	file_PnL_proto_rawDescOnce.Do(func() {
		file_PnL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PnL_proto_rawDesc), len(file_PnL_proto_rawDesc)))
	})
	return file_PnL_proto_rawDescData
}

var file_PnL_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PnL_proto_goTypes = []any{
	(*PnL)(nil), // 0: protobuf.PnL
}
var file_PnL_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PnL_proto_init() }
func file_PnL_proto_init() {
	if File_PnL_proto != nil {
		return
	}
	file_PnL_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PnL_proto_rawDesc), len(file_PnL_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PnL_proto_goTypes,
		DependencyIndexes: file_PnL_proto_depIdxs,
		MessageInfos:      file_PnL_proto_msgTypes,
	}.Build()
	File_PnL_proto = out.File
	file_PnL_proto_goTypes = nil
	file_PnL_proto_depIdxs = nil
}
