// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: PnLSingle.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PnLSingle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Position      *string                `protobuf:"bytes,2,opt,name=position,proto3,oneof" json:"position,omitempty"`
	DailyPnL      *float64               `protobuf:"fixed64,3,opt,name=dailyPnL,proto3,oneof" json:"dailyPnL,omitempty"`
	UnrealizedPnL *float64               `protobuf:"fixed64,4,opt,name=unrealizedPnL,proto3,oneof" json:"unrealizedPnL,omitempty"`
	RealizedPnL   *float64               `protobuf:"fixed64,5,opt,name=realizedPnL,proto3,oneof" json:"realizedPnL,omitempty"`
	Value         *float64               `protobuf:"fixed64,6,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PnLSingle) Reset() {
	*x = PnLSingle{}
	mi := &file_PnLSingle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PnLSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PnLSingle) ProtoMessage() {}

func (x *PnLSingle) ProtoReflect() protoreflect.Message {
	mi := &file_PnLSingle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PnLSingle.ProtoReflect.Descriptor instead.
func (*PnLSingle) Descriptor() ([]byte, []int) {
	return file_PnLSingle_proto_rawDescGZIP(), []int{0}
}

func (x *PnLSingle) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *PnLSingle) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *PnLSingle) GetDailyPnL() float64 {
	if x != nil && x.DailyPnL != nil {
		return *x.DailyPnL
	}
	return 0
}

func (x *PnLSingle) GetUnrealizedPnL() float64 {
	if x != nil && x.UnrealizedPnL != nil {
		return *x.UnrealizedPnL
	}
	return 0
}

func (x *PnLSingle) GetRealizedPnL() float64 {
	if x != nil && x.RealizedPnL != nil {
		return *x.RealizedPnL
	}
	return 0
}

func (x *PnLSingle) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_PnLSingle_proto protoreflect.FileDescriptor

const file_PnLSingle_proto_rawDesc = "" +
	"\n" +
	"\x0fPnLSingle.proto\x12\bprotobuf\"\xa5\x02\n" +
	"\tPnLSingle\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\x02 \x01(\tH\x01R\bposition\x88\x01\x01\x12\x1f\n" +
	"\bdailyPnL\x18\x03 \x01(\x01H\x02R\bdailyPnL\x88\x01\x01\x12)\n" +
	"\runrealizedPnL\x18\x04 \x01(\x01H\x03R\runrealizedPnL\x88\x01\x01\x12%\n" +
	"\vrealizedPnL\x18\x05 \x01(\x01H\x04R\vrealizedPnL\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x06 \x01(\x01H\x05R\x05value\x88\x01\x01B\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_positionB\v\n" +
	"\t_dailyPnLB\x10\n" +
	"\x0e_unrealizedPnLB\x0e\n" +
	"\f_realizedPnLB\b\n" +
	"\x06_valueB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_PnLSingle_proto_rawDescOnce sync.Once
	file_PnLSingle_proto_rawDescData []byte
)

func file_PnLSingle_proto_rawDescGZIP() []byte {
	file_PnLSingle_proto_rawDescOnce.Do(func() {
		file_PnLSingle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PnLSingle_proto_rawDesc), len(file_PnLSingle_proto_rawDesc)))
	})
	return file_PnLSingle_proto_rawDescData
}

var file_PnLSingle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PnLSingle_proto_goTypes = []any{
	(*PnLSingle)(nil), // 0: protobuf.PnLSingle
}
var file_PnLSingle_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PnLSingle_proto_init() }
func file_PnLSingle_proto_init() {
	if File_PnLSingle_proto != nil {
		return
	}
	file_PnLSingle_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PnLSingle_proto_rawDesc), len(file_PnLSingle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PnLSingle_proto_goTypes,
		DependencyIndexes: file_PnLSingle_proto_depIdxs,
		MessageInfos:      file_PnLSingle_proto_msgTypes,
	}.Build()
	File_PnLSingle_proto = out.File
	file_PnLSingle_proto_goTypes = nil
	file_PnLSingle_proto_depIdxs = nil
}
