// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: Position.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *string                `protobuf:"bytes,1,opt,name=account,proto3,oneof" json:"account,omitempty"`
	Contract      *Contract              `protobuf:"bytes,2,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
	Position      *string                `protobuf:"bytes,3,opt,name=position,proto3,oneof" json:"position,omitempty"`
	AvgCost       *float64               `protobuf:"fixed64,4,opt,name=avgCost,proto3,oneof" json:"avgCost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_Position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_Position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_Position_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *Position) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *Position) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *Position) GetAvgCost() float64 {
	if x != nil && x.AvgCost != nil {
		return *x.AvgCost
	}
	return 0
}

var File_Position_proto protoreflect.FileDescriptor

const file_Position_proto_rawDesc = "" +
	"\n" +
	"\x0ePosition.proto\x12\bprotobuf\x1a\x0eContract.proto\"\xd0\x01\n" +
	"\bPosition\x12\x1d\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x88\x01\x01\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x12.protobuf.ContractH\x01R\bcontract\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\x03 \x01(\tH\x02R\bposition\x88\x01\x01\x12\x1d\n" +
	"\aavgCost\x18\x04 \x01(\x01H\x03R\aavgCost\x88\x01\x01B\n" +
	"\n" +
	"\b_accountB\v\n" +
	"\t_contractB\v\n" +
	"\t_positionB\n" +
	"\n" +
	"\b_avgCostB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_Position_proto_rawDescOnce sync.Once
	file_Position_proto_rawDescData []byte
)

func file_Position_proto_rawDescGZIP() []byte {
	file_Position_proto_rawDescOnce.Do(func() {
		file_Position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Position_proto_rawDesc), len(file_Position_proto_rawDesc)))
	})
	return file_Position_proto_rawDescData
}

var file_Position_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Position_proto_goTypes = []any{
	(*Position)(nil), // 0: protobuf.Position
	(*Contract)(nil), // 1: protobuf.Contract
}
var file_Position_proto_depIdxs = []int32{
	1, // 0: protobuf.Position.contract:type_name -> protobuf.Contract
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Position_proto_init() }
func file_Position_proto_init() {
	if File_Position_proto != nil {
		return
	}
	file_Contract_proto_init()
	file_Position_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Position_proto_rawDesc), len(file_Position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Position_proto_goTypes,
		DependencyIndexes: file_Position_proto_depIdxs,
		MessageInfos:      file_Position_proto_msgTypes,
	}.Build()
	File_Position_proto = out.File
	file_Position_proto_goTypes = nil
	file_Position_proto_depIdxs = nil
}
