// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: RealTimeBarTick.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RealTimeBarTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	Time          *int64                 `protobuf:"varint,2,opt,name=time,proto3,oneof" json:"time,omitempty"`
	Open          *float64               `protobuf:"fixed64,3,opt,name=open,proto3,oneof" json:"open,omitempty"`
	High          *float64               `protobuf:"fixed64,4,opt,name=high,proto3,oneof" json:"high,omitempty"`
	Low           *float64               `protobuf:"fixed64,5,opt,name=low,proto3,oneof" json:"low,omitempty"`
	Close         *float64               `protobuf:"fixed64,6,opt,name=close,proto3,oneof" json:"close,omitempty"`
	Volume        *string                `protobuf:"bytes,7,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	WAP           *string                `protobuf:"bytes,8,opt,name=WAP,proto3,oneof" json:"WAP,omitempty"`
	Count         *int32                 `protobuf:"varint,9,opt,name=count,proto3,oneof" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealTimeBarTick) Reset() {
	*x = RealTimeBarTick{}
	mi := &file_RealTimeBarTick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealTimeBarTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealTimeBarTick) ProtoMessage() {}

func (x *RealTimeBarTick) ProtoReflect() protoreflect.Message {
	mi := &file_RealTimeBarTick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealTimeBarTick.ProtoReflect.Descriptor instead.
func (*RealTimeBarTick) Descriptor() ([]byte, []int) {
	return file_RealTimeBarTick_proto_rawDescGZIP(), []int{0}
}

func (x *RealTimeBarTick) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *RealTimeBarTick) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *RealTimeBarTick) GetOpen() float64 {
	if x != nil && x.Open != nil {
		return *x.Open
	}
	return 0
}

func (x *RealTimeBarTick) GetHigh() float64 {
	if x != nil && x.High != nil {
		return *x.High
	}
	return 0
}

func (x *RealTimeBarTick) GetLow() float64 {
	if x != nil && x.Low != nil {
		return *x.Low
	}
	return 0
}

func (x *RealTimeBarTick) GetClose() float64 {
	if x != nil && x.Close != nil {
		return *x.Close
	}
	return 0
}

func (x *RealTimeBarTick) GetVolume() string {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return ""
}

func (x *RealTimeBarTick) GetWAP() string {
	if x != nil && x.WAP != nil {
		return *x.WAP
	}
	return ""
}

func (x *RealTimeBarTick) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

var File_RealTimeBarTick_proto protoreflect.FileDescriptor

const file_RealTimeBarTick_proto_rawDesc = "" +
	"\n" +
	"\x15RealTimeBarTick.proto\x12\bprotobuf\"\xcc\x02\n" +
	"\x0fRealTimeBarTick\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12\x17\n" +
	"\x04time\x18\x02 \x01(\x03H\x01R\x04time\x88\x01\x01\x12\x17\n" +
	"\x04open\x18\x03 \x01(\x01H\x02R\x04open\x88\x01\x01\x12\x17\n" +
	"\x04high\x18\x04 \x01(\x01H\x03R\x04high\x88\x01\x01\x12\x15\n" +
	"\x03low\x18\x05 \x01(\x01H\x04R\x03low\x88\x01\x01\x12\x19\n" +
	"\x05close\x18\x06 \x01(\x01H\x05R\x05close\x88\x01\x01\x12\x1b\n" +
	"\x06volume\x18\a \x01(\tH\x06R\x06volume\x88\x01\x01\x12\x15\n" +
	"\x03WAP\x18\b \x01(\tH\aR\x03WAP\x88\x01\x01\x12\x19\n" +
	"\x05count\x18\t \x01(\x05H\bR\x05count\x88\x01\x01B\b\n" +
	"\x06_reqIdB\a\n" +
	"\x05_timeB\a\n" +
	"\x05_openB\a\n" +
	"\x05_highB\x06\n" +
	"\x04_lowB\b\n" +
	"\x06_closeB\t\n" +
	"\a_volumeB\x06\n" +
	"\x04_WAPB\b\n" +
	"\x06_countB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_RealTimeBarTick_proto_rawDescOnce sync.Once
	file_RealTimeBarTick_proto_rawDescData []byte
)

func file_RealTimeBarTick_proto_rawDescGZIP() []byte {
	file_RealTimeBarTick_proto_rawDescOnce.Do(func() {
		file_RealTimeBarTick_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RealTimeBarTick_proto_rawDesc), len(file_RealTimeBarTick_proto_rawDesc)))
	})
	return file_RealTimeBarTick_proto_rawDescData
}

var file_RealTimeBarTick_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RealTimeBarTick_proto_goTypes = []any{
	(*RealTimeBarTick)(nil), // 0: protobuf.RealTimeBarTick
}
var file_RealTimeBarTick_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RealTimeBarTick_proto_init() }
func file_RealTimeBarTick_proto_init() {
	if File_RealTimeBarTick_proto != nil {
		return
	}
	file_RealTimeBarTick_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RealTimeBarTick_proto_rawDesc), len(file_RealTimeBarTick_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RealTimeBarTick_proto_goTypes,
		DependencyIndexes: file_RealTimeBarTick_proto_depIdxs,
		MessageInfos:      file_RealTimeBarTick_proto_msgTypes,
	}.Build()
	File_RealTimeBarTick_proto = out.File
	file_RealTimeBarTick_proto_goTypes = nil
	file_RealTimeBarTick_proto_depIdxs = nil
}
