// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: ScannerParameters.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScannerParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xml           *string                `protobuf:"bytes,1,opt,name=xml,proto3,oneof" json:"xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerParameters) Reset() {
	*x = ScannerParameters{}
	mi := &file_ScannerParameters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerParameters) ProtoMessage() {}

func (x *ScannerParameters) ProtoReflect() protoreflect.Message {
	mi := &file_ScannerParameters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerParameters.ProtoReflect.Descriptor instead.
func (*ScannerParameters) Descriptor() ([]byte, []int) {
	return file_ScannerParameters_proto_rawDescGZIP(), []int{0}
}

func (x *ScannerParameters) GetXml() string {
	if x != nil && x.Xml != nil {
		return *x.Xml
	}
	return ""
}

var File_ScannerParameters_proto protoreflect.FileDescriptor

const file_ScannerParameters_proto_rawDesc = "" +
	"\n" +
	"\x17ScannerParameters.proto\x12\bprotobuf\"2\n" +
	"\x11ScannerParameters\x12\x15\n" +
	"\x03xml\x18\x01 \x01(\tH\x00R\x03xml\x88\x01\x01B\x06\n" +
	"\x04_xmlB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_ScannerParameters_proto_rawDescOnce sync.Once
	file_ScannerParameters_proto_rawDescData []byte
)

func file_ScannerParameters_proto_rawDescGZIP() []byte {
	file_ScannerParameters_proto_rawDescOnce.Do(func() {
		file_ScannerParameters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ScannerParameters_proto_rawDesc), len(file_ScannerParameters_proto_rawDesc)))
	})
	return file_ScannerParameters_proto_rawDescData
}

var file_ScannerParameters_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ScannerParameters_proto_goTypes = []any{
	(*ScannerParameters)(nil), // 0: protobuf.ScannerParameters
}
var file_ScannerParameters_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ScannerParameters_proto_init() }
func file_ScannerParameters_proto_init() {
	if File_ScannerParameters_proto != nil {
		return
	}
	file_ScannerParameters_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ScannerParameters_proto_rawDesc), len(file_ScannerParameters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ScannerParameters_proto_goTypes,
		DependencyIndexes: file_ScannerParameters_proto_depIdxs,
		MessageInfos:      file_ScannerParameters_proto_msgTypes,
	}.Build()
	File_ScannerParameters_proto = out.File
	file_ScannerParameters_proto_goTypes = nil
	file_ScannerParameters_proto_depIdxs = nil
}
