// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: SecDefOptParamsRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecDefOptParamsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReqId             *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	UnderlyingSymbol  *string                `protobuf:"bytes,2,opt,name=underlyingSymbol,proto3,oneof" json:"underlyingSymbol,omitempty"`
	FutFopExchange    *string                `protobuf:"bytes,3,opt,name=futFopExchange,proto3,oneof" json:"futFopExchange,omitempty"`
	UnderlyingSecType *string                `protobuf:"bytes,4,opt,name=underlyingSecType,proto3,oneof" json:"underlyingSecType,omitempty"`
	UnderlyingConId   *int32                 `protobuf:"varint,5,opt,name=underlyingConId,proto3,oneof" json:"underlyingConId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SecDefOptParamsRequest) Reset() {
	*x = SecDefOptParamsRequest{}
	mi := &file_SecDefOptParamsRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecDefOptParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecDefOptParamsRequest) ProtoMessage() {}

func (x *SecDefOptParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SecDefOptParamsRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecDefOptParamsRequest.ProtoReflect.Descriptor instead.
func (*SecDefOptParamsRequest) Descriptor() ([]byte, []int) {
	return file_SecDefOptParamsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *SecDefOptParamsRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *SecDefOptParamsRequest) GetUnderlyingSymbol() string {
	if x != nil && x.UnderlyingSymbol != nil {
		return *x.UnderlyingSymbol
	}
	return ""
}

func (x *SecDefOptParamsRequest) GetFutFopExchange() string {
	if x != nil && x.FutFopExchange != nil {
		return *x.FutFopExchange
	}
	return ""
}

func (x *SecDefOptParamsRequest) GetUnderlyingSecType() string {
	if x != nil && x.UnderlyingSecType != nil {
		return *x.UnderlyingSecType
	}
	return ""
}

func (x *SecDefOptParamsRequest) GetUnderlyingConId() int32 {
	if x != nil && x.UnderlyingConId != nil {
		return *x.UnderlyingConId
	}
	return 0
}

var File_SecDefOptParamsRequest_proto protoreflect.FileDescriptor

const file_SecDefOptParamsRequest_proto_rawDesc = "" +
	"\n" +
	"\x1cSecDefOptParamsRequest.proto\x12\bprotobuf\"\xcf\x02\n" +
	"\x16SecDefOptParamsRequest\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12/\n" +
	"\x10underlyingSymbol\x18\x02 \x01(\tH\x01R\x10underlyingSymbol\x88\x01\x01\x12+\n" +
	"\x0efutFopExchange\x18\x03 \x01(\tH\x02R\x0efutFopExchange\x88\x01\x01\x121\n" +
	"\x11underlyingSecType\x18\x04 \x01(\tH\x03R\x11underlyingSecType\x88\x01\x01\x12-\n" +
	"\x0funderlyingConId\x18\x05 \x01(\x05H\x04R\x0funderlyingConId\x88\x01\x01B\b\n" +
	"\x06_reqIdB\x13\n" +
	"\x11_underlyingSymbolB\x11\n" +
	"\x0f_futFopExchangeB\x14\n" +
	"\x12_underlyingSecTypeB\x12\n" +
	"\x10_underlyingConIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_SecDefOptParamsRequest_proto_rawDescOnce sync.Once
	file_SecDefOptParamsRequest_proto_rawDescData []byte
)

func file_SecDefOptParamsRequest_proto_rawDescGZIP() []byte {
	file_SecDefOptParamsRequest_proto_rawDescOnce.Do(func() {
		file_SecDefOptParamsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SecDefOptParamsRequest_proto_rawDesc), len(file_SecDefOptParamsRequest_proto_rawDesc)))
	})
	return file_SecDefOptParamsRequest_proto_rawDescData
}

var file_SecDefOptParamsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SecDefOptParamsRequest_proto_goTypes = []any{
	(*SecDefOptParamsRequest)(nil), // 0: protobuf.SecDefOptParamsRequest
}
var file_SecDefOptParamsRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SecDefOptParamsRequest_proto_init() }
func file_SecDefOptParamsRequest_proto_init() {
	if File_SecDefOptParamsRequest_proto != nil {
		return
	}
	file_SecDefOptParamsRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SecDefOptParamsRequest_proto_rawDesc), len(file_SecDefOptParamsRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SecDefOptParamsRequest_proto_goTypes,
		DependencyIndexes: file_SecDefOptParamsRequest_proto_depIdxs,
		MessageInfos:      file_SecDefOptParamsRequest_proto_msgTypes,
	}.Build()
	File_SecDefOptParamsRequest_proto = out.File
	file_SecDefOptParamsRequest_proto_goTypes = nil
	file_SecDefOptParamsRequest_proto_depIdxs = nil
}
