// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: SecDefOptParameterEnd.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecDefOptParameterEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecDefOptParameterEnd) Reset() {
	*x = SecDefOptParameterEnd{}
	mi := &file_SecDefOptParameterEnd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecDefOptParameterEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecDefOptParameterEnd) ProtoMessage() {}

func (x *SecDefOptParameterEnd) ProtoReflect() protoreflect.Message {
	mi := &file_SecDefOptParameterEnd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecDefOptParameterEnd.ProtoReflect.Descriptor instead.
func (*SecDefOptParameterEnd) Descriptor() ([]byte, []int) {
	return file_SecDefOptParameterEnd_proto_rawDescGZIP(), []int{0}
}

func (x *SecDefOptParameterEnd) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

var File_SecDefOptParameterEnd_proto protoreflect.FileDescriptor

const file_SecDefOptParameterEnd_proto_rawDesc = "" +
	"\n" +
	"\x1bSecDefOptParameterEnd.proto\x12\bprotobuf\"<\n" +
	"\x15SecDefOptParameterEnd\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01B\b\n" +
	"\x06_reqIdB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_SecDefOptParameterEnd_proto_rawDescOnce sync.Once
	file_SecDefOptParameterEnd_proto_rawDescData []byte
)

func file_SecDefOptParameterEnd_proto_rawDescGZIP() []byte {
	file_SecDefOptParameterEnd_proto_rawDescOnce.Do(func() {
		file_SecDefOptParameterEnd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SecDefOptParameterEnd_proto_rawDesc), len(file_SecDefOptParameterEnd_proto_rawDesc)))
	})
	return file_SecDefOptParameterEnd_proto_rawDescData
}

var file_SecDefOptParameterEnd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SecDefOptParameterEnd_proto_goTypes = []any{
	(*SecDefOptParameterEnd)(nil), // 0: protobuf.SecDefOptParameterEnd
}
var file_SecDefOptParameterEnd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SecDefOptParameterEnd_proto_init() }
func file_SecDefOptParameterEnd_proto_init() {
	if File_SecDefOptParameterEnd_proto != nil {
		return
	}
	file_SecDefOptParameterEnd_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SecDefOptParameterEnd_proto_rawDesc), len(file_SecDefOptParameterEnd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SecDefOptParameterEnd_proto_goTypes,
		DependencyIndexes: file_SecDefOptParameterEnd_proto_depIdxs,
		MessageInfos:      file_SecDefOptParameterEnd_proto_msgTypes,
	}.Build()
	File_SecDefOptParameterEnd_proto = out.File
	file_SecDefOptParameterEnd_proto_goTypes = nil
	file_SecDefOptParameterEnd_proto_depIdxs = nil
}
