// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: SymbolSamples.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SymbolSamples struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ReqId                *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	ContractDescriptions []*ContractDescription `protobuf:"bytes,2,rep,name=contractDescriptions,proto3" json:"contractDescriptions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SymbolSamples) Reset() {
	*x = SymbolSamples{}
	mi := &file_SymbolSamples_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolSamples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolSamples) ProtoMessage() {}

func (x *SymbolSamples) ProtoReflect() protoreflect.Message {
	mi := &file_SymbolSamples_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolSamples.ProtoReflect.Descriptor instead.
func (*SymbolSamples) Descriptor() ([]byte, []int) {
	return file_SymbolSamples_proto_rawDescGZIP(), []int{0}
}

func (x *SymbolSamples) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *SymbolSamples) GetContractDescriptions() []*ContractDescription {
	if x != nil {
		return x.ContractDescriptions
	}
	return nil
}

var File_SymbolSamples_proto protoreflect.FileDescriptor

var file_SymbolSamples_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a,
	0x19, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x0d, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x05,
	0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x72,
	0x65, 0x71, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x51, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72,
	0x65, 0x71, 0x49, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_SymbolSamples_proto_rawDescOnce sync.Once
	file_SymbolSamples_proto_rawDescData []byte
)

func file_SymbolSamples_proto_rawDescGZIP() []byte {
	file_SymbolSamples_proto_rawDescOnce.Do(func() {
		file_SymbolSamples_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SymbolSamples_proto_rawDesc), len(file_SymbolSamples_proto_rawDesc)))
	})
	return file_SymbolSamples_proto_rawDescData
}

var file_SymbolSamples_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SymbolSamples_proto_goTypes = []any{
	(*SymbolSamples)(nil),       // 0: protobuf.SymbolSamples
	(*ContractDescription)(nil), // 1: protobuf.ContractDescription
}
var file_SymbolSamples_proto_depIdxs = []int32{
	1, // 0: protobuf.SymbolSamples.contractDescriptions:type_name -> protobuf.ContractDescription
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SymbolSamples_proto_init() }
func file_SymbolSamples_proto_init() {
	if File_SymbolSamples_proto != nil {
		return
	}
	file_ContractDescription_proto_init()
	file_SymbolSamples_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SymbolSamples_proto_rawDesc), len(file_SymbolSamples_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SymbolSamples_proto_goTypes,
		DependencyIndexes: file_SymbolSamples_proto_depIdxs,
		MessageInfos:      file_SymbolSamples_proto_msgTypes,
	}.Build()
	File_SymbolSamples_proto = out.File
	file_SymbolSamples_proto_goTypes = nil
	file_SymbolSamples_proto_depIdxs = nil
}
