// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: TickPrice.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	TickType      *int32                 `protobuf:"varint,2,opt,name=tickType,proto3,oneof" json:"tickType,omitempty"`
	Price         *float64               `protobuf:"fixed64,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Size          *string                `protobuf:"bytes,4,opt,name=size,proto3,oneof" json:"size,omitempty"`
	AttrMask      *int32                 `protobuf:"varint,5,opt,name=attrMask,proto3,oneof" json:"attrMask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickPrice) Reset() {
	*x = TickPrice{}
	mi := &file_TickPrice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickPrice) ProtoMessage() {}

func (x *TickPrice) ProtoReflect() protoreflect.Message {
	mi := &file_TickPrice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickPrice.ProtoReflect.Descriptor instead.
func (*TickPrice) Descriptor() ([]byte, []int) {
	return file_TickPrice_proto_rawDescGZIP(), []int{0}
}

func (x *TickPrice) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *TickPrice) GetTickType() int32 {
	if x != nil && x.TickType != nil {
		return *x.TickType
	}
	return 0
}

func (x *TickPrice) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *TickPrice) GetSize() string {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return ""
}

func (x *TickPrice) GetAttrMask() int32 {
	if x != nil && x.AttrMask != nil {
		return *x.AttrMask
	}
	return 0
}

var File_TickPrice_proto protoreflect.FileDescriptor

const file_TickPrice_proto_rawDesc = "" +
	"\n" +
	"\x0fTickPrice.proto\x12\bprotobuf\"\xd3\x01\n" +
	"\tTickPrice\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01\x12\x1f\n" +
	"\btickType\x18\x02 \x01(\x05H\x01R\btickType\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x01H\x02R\x05price\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x04 \x01(\tH\x03R\x04size\x88\x01\x01\x12\x1f\n" +
	"\battrMask\x18\x05 \x01(\x05H\x04R\battrMask\x88\x01\x01B\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_tickTypeB\b\n" +
	"\x06_priceB\a\n" +
	"\x05_sizeB\v\n" +
	"\t_attrMaskB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_TickPrice_proto_rawDescOnce sync.Once
	file_TickPrice_proto_rawDescData []byte
)

func file_TickPrice_proto_rawDescGZIP() []byte {
	file_TickPrice_proto_rawDescOnce.Do(func() {
		file_TickPrice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TickPrice_proto_rawDesc), len(file_TickPrice_proto_rawDesc)))
	})
	return file_TickPrice_proto_rawDescData
}

var file_TickPrice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TickPrice_proto_goTypes = []any{
	(*TickPrice)(nil), // 0: protobuf.TickPrice
}
var file_TickPrice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TickPrice_proto_init() }
func file_TickPrice_proto_init() {
	if File_TickPrice_proto != nil {
		return
	}
	file_TickPrice_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TickPrice_proto_rawDesc), len(file_TickPrice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TickPrice_proto_goTypes,
		DependencyIndexes: file_TickPrice_proto_depIdxs,
		MessageInfos:      file_TickPrice_proto_msgTypes,
	}.Build()
	File_TickPrice_proto = out.File
	file_TickPrice_proto_goTypes = nil
	file_TickPrice_proto_depIdxs = nil
}
