// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: TickByTickData.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickByTickData struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ReqId    *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	TickType *int32                 `protobuf:"varint,2,opt,name=tickType,proto3,oneof" json:"tickType,omitempty"`
	// Types that are valid to be assigned to Tick:
	//
	//	*TickByTickData_HistoricalTickLast
	//	*TickByTickData_HistoricalTickBidAsk
	//	*TickByTickData_HistoricalTickMidPoint
	Tick          isTickByTickData_Tick `protobuf_oneof:"tick"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickByTickData) Reset() {
	*x = TickByTickData{}
	mi := &file_TickByTickData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickByTickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickByTickData) ProtoMessage() {}

func (x *TickByTickData) ProtoReflect() protoreflect.Message {
	mi := &file_TickByTickData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickByTickData.ProtoReflect.Descriptor instead.
func (*TickByTickData) Descriptor() ([]byte, []int) {
	return file_TickByTickData_proto_rawDescGZIP(), []int{0}
}

func (x *TickByTickData) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *TickByTickData) GetTickType() int32 {
	if x != nil && x.TickType != nil {
		return *x.TickType
	}
	return 0
}

func (x *TickByTickData) GetTick() isTickByTickData_Tick {
	if x != nil {
		return x.Tick
	}
	return nil
}

func (x *TickByTickData) GetHistoricalTickLast() *HistoricalTickLast {
	if x != nil {
		if x, ok := x.Tick.(*TickByTickData_HistoricalTickLast); ok {
			return x.HistoricalTickLast
		}
	}
	return nil
}

func (x *TickByTickData) GetHistoricalTickBidAsk() *HistoricalTickBidAsk {
	if x != nil {
		if x, ok := x.Tick.(*TickByTickData_HistoricalTickBidAsk); ok {
			return x.HistoricalTickBidAsk
		}
	}
	return nil
}

func (x *TickByTickData) GetHistoricalTickMidPoint() *HistoricalTick {
	if x != nil {
		if x, ok := x.Tick.(*TickByTickData_HistoricalTickMidPoint); ok {
			return x.HistoricalTickMidPoint
		}
	}
	return nil
}

type isTickByTickData_Tick interface {
	isTickByTickData_Tick()
}

type TickByTickData_HistoricalTickLast struct {
	HistoricalTickLast *HistoricalTickLast `protobuf:"bytes,3,opt,name=historicalTickLast,proto3,oneof"`
}

type TickByTickData_HistoricalTickBidAsk struct {
	HistoricalTickBidAsk *HistoricalTickBidAsk `protobuf:"bytes,4,opt,name=historicalTickBidAsk,proto3,oneof"`
}

type TickByTickData_HistoricalTickMidPoint struct {
	HistoricalTickMidPoint *HistoricalTick `protobuf:"bytes,5,opt,name=historicalTickMidPoint,proto3,oneof"`
}

func (*TickByTickData_HistoricalTickLast) isTickByTickData_Tick() {}

func (*TickByTickData_HistoricalTickBidAsk) isTickByTickData_Tick() {}

func (*TickByTickData_HistoricalTickMidPoint) isTickByTickData_Tick() {}

var File_TickByTickData_proto protoreflect.FileDescriptor

const file_TickByTickData_proto_rawDesc = "" +
	"\n" +
	"\x14TickByTickData.proto\x12\bprotobuf\x1a\x14HistoricalTick.proto\x1a\x1aHistoricalTickBidAsk.proto\x1a\x18HistoricalTickLast.proto\"\xe5\x02\n" +
	"\x0eTickByTickData\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x01R\x05reqId\x88\x01\x01\x12\x1f\n" +
	"\btickType\x18\x02 \x01(\x05H\x02R\btickType\x88\x01\x01\x12N\n" +
	"\x12historicalTickLast\x18\x03 \x01(\v2\x1c.protobuf.HistoricalTickLastH\x00R\x12historicalTickLast\x12T\n" +
	"\x14historicalTickBidAsk\x18\x04 \x01(\v2\x1e.protobuf.HistoricalTickBidAskH\x00R\x14historicalTickBidAsk\x12R\n" +
	"\x16historicalTickMidPoint\x18\x05 \x01(\v2\x18.protobuf.HistoricalTickH\x00R\x16historicalTickMidPointB\x06\n" +
	"\x04tickB\b\n" +
	"\x06_reqIdB\v\n" +
	"\t_tickTypeB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_TickByTickData_proto_rawDescOnce sync.Once
	file_TickByTickData_proto_rawDescData []byte
)

func file_TickByTickData_proto_rawDescGZIP() []byte {
	file_TickByTickData_proto_rawDescOnce.Do(func() {
		file_TickByTickData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TickByTickData_proto_rawDesc), len(file_TickByTickData_proto_rawDesc)))
	})
	return file_TickByTickData_proto_rawDescData
}

var file_TickByTickData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TickByTickData_proto_goTypes = []any{
	(*TickByTickData)(nil),       // 0: protobuf.TickByTickData
	(*HistoricalTickLast)(nil),   // 1: protobuf.HistoricalTickLast
	(*HistoricalTickBidAsk)(nil), // 2: protobuf.HistoricalTickBidAsk
	(*HistoricalTick)(nil),       // 3: protobuf.HistoricalTick
}
var file_TickByTickData_proto_depIdxs = []int32{
	1, // 0: protobuf.TickByTickData.historicalTickLast:type_name -> protobuf.HistoricalTickLast
	2, // 1: protobuf.TickByTickData.historicalTickBidAsk:type_name -> protobuf.HistoricalTickBidAsk
	3, // 2: protobuf.TickByTickData.historicalTickMidPoint:type_name -> protobuf.HistoricalTick
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TickByTickData_proto_init() }
func file_TickByTickData_proto_init() {
	if File_TickByTickData_proto != nil {
		return
	}
	file_HistoricalTick_proto_init()
	file_HistoricalTickBidAsk_proto_init()
	file_HistoricalTickLast_proto_init()
	file_TickByTickData_proto_msgTypes[0].OneofWrappers = []any{
		(*TickByTickData_HistoricalTickLast)(nil),
		(*TickByTickData_HistoricalTickBidAsk)(nil),
		(*TickByTickData_HistoricalTickMidPoint)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TickByTickData_proto_rawDesc), len(file_TickByTickData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TickByTickData_proto_goTypes,
		DependencyIndexes: file_TickByTickData_proto_depIdxs,
		MessageInfos:      file_TickByTickData_proto_msgTypes,
	}.Build()
	File_TickByTickData_proto = out.File
	file_TickByTickData_proto_goTypes = nil
	file_TickByTickData_proto_depIdxs = nil
}
