// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: VerifyCompleted.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccessful  *bool                  `protobuf:"varint,1,opt,name=isSuccessful,proto3,oneof" json:"isSuccessful,omitempty"`
	ErrorText     *string                `protobuf:"bytes,2,opt,name=errorText,proto3,oneof" json:"errorText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCompleted) Reset() {
	*x = VerifyCompleted{}
	mi := &file_VerifyCompleted_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCompleted) ProtoMessage() {}

func (x *VerifyCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_VerifyCompleted_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCompleted.ProtoReflect.Descriptor instead.
func (*VerifyCompleted) Descriptor() ([]byte, []int) {
	return file_VerifyCompleted_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyCompleted) GetIsSuccessful() bool {
	if x != nil && x.IsSuccessful != nil {
		return *x.IsSuccessful
	}
	return false
}

func (x *VerifyCompleted) GetErrorText() string {
	if x != nil && x.ErrorText != nil {
		return *x.ErrorText
	}
	return ""
}

var File_VerifyCompleted_proto protoreflect.FileDescriptor

var file_VerifyCompleted_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x22, 0x7c, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0c, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x73,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01,
	0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75,
	0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x65, 0x78, 0x74, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_VerifyCompleted_proto_rawDescOnce sync.Once
	file_VerifyCompleted_proto_rawDescData []byte
)

func file_VerifyCompleted_proto_rawDescGZIP() []byte {
	file_VerifyCompleted_proto_rawDescOnce.Do(func() {
		file_VerifyCompleted_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_VerifyCompleted_proto_rawDesc), len(file_VerifyCompleted_proto_rawDesc)))
	})
	return file_VerifyCompleted_proto_rawDescData
}

var file_VerifyCompleted_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_VerifyCompleted_proto_goTypes = []any{
	(*VerifyCompleted)(nil), // 0: protobuf.VerifyCompleted
}
var file_VerifyCompleted_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_VerifyCompleted_proto_init() }
func file_VerifyCompleted_proto_init() {
	if File_VerifyCompleted_proto != nil {
		return
	}
	file_VerifyCompleted_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_VerifyCompleted_proto_rawDesc), len(file_VerifyCompleted_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_VerifyCompleted_proto_goTypes,
		DependencyIndexes: file_VerifyCompleted_proto_depIdxs,
		MessageInfos:      file_VerifyCompleted_proto_msgTypes,
	}.Build()
	File_VerifyCompleted_proto = out.File
	file_VerifyCompleted_proto_goTypes = nil
	file_VerifyCompleted_proto_depIdxs = nil
}
