// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: VerifyRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiName       *string                `protobuf:"bytes,1,opt,name=apiName,proto3,oneof" json:"apiName,omitempty"`
	ApiVersion    *string                `protobuf:"bytes,2,opt,name=apiVersion,proto3,oneof" json:"apiVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_VerifyRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_VerifyRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_VerifyRequest_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetApiName() string {
	if x != nil && x.ApiName != nil {
		return *x.ApiName
	}
	return ""
}

func (x *VerifyRequest) GetApiVersion() string {
	if x != nil && x.ApiVersion != nil {
		return *x.ApiVersion
	}
	return ""
}

var File_VerifyRequest_proto protoreflect.FileDescriptor

const file_VerifyRequest_proto_rawDesc = "" +
	"\n" +
	"\x13VerifyRequest.proto\x12\bprotobuf\"n\n" +
	"\rVerifyRequest\x12\x1d\n" +
	"\aapiName\x18\x01 \x01(\tH\x00R\aapiName\x88\x01\x01\x12#\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tH\x01R\n" +
	"apiVersion\x88\x01\x01B\n" +
	"\n" +
	"\b_apiNameB\r\n" +
	"\v_apiVersionB\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_VerifyRequest_proto_rawDescOnce sync.Once
	file_VerifyRequest_proto_rawDescData []byte
)

func file_VerifyRequest_proto_rawDescGZIP() []byte {
	file_VerifyRequest_proto_rawDescOnce.Do(func() {
		file_VerifyRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_VerifyRequest_proto_rawDesc), len(file_VerifyRequest_proto_rawDesc)))
	})
	return file_VerifyRequest_proto_rawDescData
}

var file_VerifyRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_VerifyRequest_proto_goTypes = []any{
	(*VerifyRequest)(nil), // 0: protobuf.VerifyRequest
}
var file_VerifyRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_VerifyRequest_proto_init() }
func file_VerifyRequest_proto_init() {
	if File_VerifyRequest_proto != nil {
		return
	}
	file_VerifyRequest_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_VerifyRequest_proto_rawDesc), len(file_VerifyRequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_VerifyRequest_proto_goTypes,
		DependencyIndexes: file_VerifyRequest_proto_depIdxs,
		MessageInfos:      file_VerifyRequest_proto_msgTypes,
	}.Build()
	File_VerifyRequest_proto = out.File
	file_VerifyRequest_proto_goTypes = nil
	file_VerifyRequest_proto_depIdxs = nil
}
